In [613]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [614]:
data=pd.read_csv("before_cleaning_data_sales.csv")

In [615]:
data.columns

Index(['Transaction ID', 'Item', 'Quantity', 'Price Per Unit', 'Total Spent',
       'Payment Method', 'Location', 'Transaction Date'],
      dtype='object')

In [616]:
for i in data.columns:
    print(i)

Transaction ID
Item
Quantity
Price Per Unit
Total Spent
Payment Method
Location
Transaction Date

In [617]:
print(list(data.columns))

['Transaction ID', 'Item', 'Quantity', 'Price Per Unit', 'Total Spent', 'Payment Method', 'Location', 'Transaction Date']

In [618]:
  # the columns data convert into the upper case
new_col=[]
for i in data.columns:
    new_col.append(i.upper())

In [619]:
new_col

['TRANSACTION ID',
 'ITEM',
 'QUANTITY',
 'PRICE PER UNIT',
 'TOTAL SPENT',
 'PAYMENT METHOD',
 'LOCATION',
 'TRANSACTION DATE']

In [620]:
new_data=data.copy()

In [621]:
new_data.columns=new_col

In [622]:
new_data

,TRANSACTION ID,ITEM,QUANTITY,PRICE PER UNIT,TOTAL SPENT,PAYMENT METHOD,LOCATION,TRANSACTION DATE
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [623]:
# agarn convert the columns in lower case
new_data.columns

Index(['TRANSACTION ID', 'ITEM', 'QUANTITY', 'PRICE PER UNIT', 'TOTAL SPENT',
       'PAYMENT METHOD', 'LOCATION', 'TRANSACTION DATE'],
      dtype='object')

In [624]:
for i in new_data.columns:
    print(i)

TRANSACTION ID
ITEM
QUANTITY
PRICE PER UNIT
TOTAL SPENT
PAYMENT METHOD
LOCATION
TRANSACTION DATE

In [625]:
list(new_data.columns)

['TRANSACTION ID',
 'ITEM',
 'QUANTITY',
 'PRICE PER UNIT',
 'TOTAL SPENT',
 'PAYMENT METHOD',
 'LOCATION',
 'TRANSACTION DATE']

In [626]:
new_data

,TRANSACTION ID,ITEM,QUANTITY,PRICE PER UNIT,TOTAL SPENT,PAYMENT METHOD,LOCATION,TRANSACTION DATE
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [627]:
# novert into into the lower case
lower=[]
for i in new_data.columns:
    lower.append(i.lower())

In [628]:
lower

['transaction id',
 'item',
 'quantity',
 'price per unit',
 'total spent',
 'payment method',
 'location',
 'transaction date']

In [629]:
lower_copy=new_data.copy()

In [630]:
lower_copy.columns=lower

In [631]:
lower_copy

,transaction id,item,quantity,price per unit,total spent,payment method,location,transaction date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [632]:
lower_copy.columns

Index(['transaction id', 'item', 'quantity', 'price per unit', 'total spent',
       'payment method', 'location', 'transaction date'],
      dtype='object')

In [633]:
lower_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction id    10000 non-null  object
 1   item              9667 non-null   object
 2   quantity          9862 non-null   object
 3   price per unit    9821 non-null   object
 4   total spent       9827 non-null   object
 5   payment method    7421 non-null   object
 6   location          6735 non-null   object
 7   transaction date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

In [634]:
lower_copy.isnull().sum()

transaction id         0
item                 333
quantity             138
price per unit       179
total spent          173
payment method      2579
location            3265
transaction date     159
dtype: int64

In [635]:
# i am working in the columns (item.     ) 
lower_copy["item"].value_counts()

item
Juice       1171
Coffee      1165
Salad       1148
Cake        1139
Sandwich    1131
Smoothie    1096
Cookie      1092
Tea         1089
UNKNOWN      344
ERROR        292
Name: count, dtype: int64

In [636]:
print((1171+1165+1148+1139+1131+1096+1092+1089+344+292)/10)

966.7

In [637]:
 #966.7 "the its value the nearest in the ,"tea" data thats whty i fill the tea of null value

In [638]:
lower_copy["item"]=lower_copy["item"].fillna("Tea")

In [639]:
lower_copy["item"].value_counts().sum()

np.int64(10000)

In [640]:
lower_copy.isnull().sum()

transaction id         0
item                   0
quantity             138
price per unit       179
total spent          173
payment method      2579
location            3265
transaction date     159
dtype: int64

In [641]:
 # now i am working in the the columns lower_copy["quantity"]
lower_copy["quantity"].value_counts()

quantity
5          2013
2          1974
4          1863
3          1849
1          1822
UNKNOWN     171
ERROR       170
Name: count, dtype: int64

In [642]:
print((2013+1974+1863+1849+1822+171+170)/7)

1408.857142857143

In [643]:
lower_copy["quantity"]=lower_copy["quantity"].fillna(1)

In [644]:
lower_copy["quantity"].isnull().sum()

np.int64(0)

In [645]:
lower_copy["quantity"].value_counts()

quantity
5          2013
2          1974
4          1863
3          1849
1          1822
UNKNOWN     171
ERROR       170
1           138
Name: count, dtype: int64

In [646]:
type(lower_copy["quantity"][9000])

str

In [647]:
lower_copy["quantity"]=lower_copy["quantity"].str.replace("UNKNOWN","0")

In [648]:
lower_copy["quantity"]=lower_copy["quantity"].str.replace("ERROR","0")

In [649]:
lower_copy["quantity"].value_counts()

quantity
5    2013
2    1974
4    1863
3    1849
1    1822
0     341
Name: count, dtype: int64

In [650]:
 # to convert the data tyepe
lower_copy["quantity"].fillna

<bound method NDFrame.fillna of 0       2
1       4
2       4
3       2
4       2
       ..
9995    2
9996    3
9997    4
9998    3
9999    3
Name: quantity, Length: 10000, dtype: object>

In [651]:
lower_copy["quantity"]=lower_copy["quantity"].astype(int)

ValueError: cannot convert float NaN to integer

In [652]:
lower_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction id    10000 non-null  object
 1   item              10000 non-null  object
 2   quantity          9862 non-null   object
 3   price per unit    9821 non-null   object
 4   total spent       9827 non-null   object
 5   payment method    7421 non-null   object
 6   location          6735 non-null   object
 7   transaction date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

In [653]:
lower_copy.isnull().sum()

transaction id         0
item                   0
quantity             138
price per unit       179
total spent          173
payment method      2579
location            3265
transaction date     159
dtype: int64

In [654]:
# know working in the the columns (price per unit)

In [655]:
lower_copy["price per unit"].isnull().sum()

np.int64(179)

In [656]:
lower_copy["price per unit"].value_counts()

price per unit
3.0        2429
4.0        2331
2.0        1227
5.0        1204
1.0        1143
1.5        1133
ERROR       190
UNKNOWN     164
Name: count, dtype: int64

In [657]:
print((2429+2331+1227+1204+1143+1133)/6)

1577.8333333333333

In [658]:
type(lower_copy["price per unit"][90])

str

In [659]:
lower_copy["price per unit"]=lower_copy["price per unit"].fillna(2.0)

In [660]:
lower_copy["price per unit"].value_counts()

price per unit
3.0        2429
4.0        2331
2.0        1227
5.0        1204
1.0        1143
1.5        1133
ERROR       190
2.0         179
UNKNOWN     164
Name: count, dtype: int64

In [661]:
lower_copy["price per unit"]=lower_copy["price per unit"].str.replace("ERROR","0")

In [662]:
lower_copy["price per unit"]=lower_copy["price per unit"].str.replace("UNKNOWN","0")

In [663]:
lower_copy["price per unit"].value_counts().sum()

np.int64(9821)

In [664]:
lower_copy["price per unit"].isnull().sum()

np.int64(179)

In [665]:
lower_copy["price per unit"]=lower_copy["price per unit"].fillna(2.0)

In [666]:
lower_copy["price per unit"].isnull().sum()

np.int64(0)

In [667]:
lower_copy["price per unit"].value_counts()

price per unit
3.0    2429
4.0    2331
2.0    1227
5.0    1204
1.0    1143
1.5    1133
0       354
2.0     179
Name: count, dtype: int64

In [668]:
 # To convert the data type()

In [669]:
lower_copy["price per unit"]=lower_copy["price per unit"].astype(float)

In [670]:
lower_copy["price per unit"].value_counts().sum()

np.int64(10000)

In [671]:
lower_copy["price per unit"].value_counts()

price per unit
3.0    2429
4.0    2331
2.0    1406
5.0    1204
1.0    1143
1.5    1133
0.0     354
Name: count, dtype: int64

In [672]:
lower_copy["price per unit"].isnull().sum()

np.int64(0)

In [673]:
lower_copy.isnull().sum()

transaction id         0
item                   0
quantity             138
price per unit         0
total spent          173
payment method      2579
location            3265
transaction date     159
dtype: int64

In [674]:
lower_copy["quantity"].isnull().sum()

np.int64(138)

In [675]:
lower_copy["quantity"].value_counts()

quantity
5    2013
2    1974
4    1863
3    1849
1    1822
0     341
Name: count, dtype: int64

In [676]:
print((2013+1974+1863+1849+1822+341)/6)

1643.6666666666667

In [677]:
lower_copy["quantity"]=lower_copy["quantity"].fillna(1)

In [678]:
lower_copy["quantity"].value_counts()
lower_copy["quantity"].isnull().sum()

np.int64(0)

In [679]:
lower_copy["quantity"]=lower_copy["quantity"].astype(int)

In [680]:
lower_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction id    10000 non-null  object
 1   item              10000 non-null  object
 2   quantity          10000 non-null  int64
 3   price per unit    10000 non-null  float64
 4   total spent       9827 non-null   object
 5   payment method    7421 non-null   object
 6   location          6735 non-null   object
 7   transaction date  9841 non-null   object
dtypes: float64(1), int64(1), object(6)
memory usage: 625.1+ KB

In [681]:
lower_copy.isnull().sum()

transaction id         0
item                   0
quantity               0
price per unit         0
total spent          173
payment method      2579
location            3265
transaction date     159
dtype: int64

In [682]:
# know i am working in the the column lower_copy["total spent"]

In [683]:
lower_copy["total spent"]
type(lower_copy["total spent"][90])
lower_copy["total spent"].value_counts()

total spent
6.0        979
12.0       939
3.0        930
4.0        923
20.0       746
15.0       734
8.0        677
10.0       524
2.0        497
9.0        479
5.0        468
16.0       444
25.0       259
7.5        237
1.0        232
4.5        225
1.5        205
UNKNOWN    165
ERROR      164
Name: count, dtype: int64

In [684]:
lower_copy["total spent"]=lower_copy["total spent"].str.replace("UNKNOWN","0")

In [685]:
lower_copy["total spent"]=lower_copy["total spent"].str.replace("ERROR","0")

In [686]:
lower_copy["total spent"].isnull().sum()

np.int64(173)

In [687]:
print((939+930+923+746+734+677+524+497+479+468+444+329+259+237+232+225+205)/17)

520.4705882352941

In [688]:
lower_copy["total spent"]=lower_copy["total spent"].fillna(10.0)

In [689]:
type(lower_copy["total spent"][0])

str

In [690]:
lower_copy["total spent"]=lower_copy["total spent"].astype(float)

In [691]:
lower_copy.isnull().sum()

transaction id         0
item                   0
quantity               0
price per unit         0
total spent            0
payment method      2579
location            3265
transaction date     159
dtype: int64

In [692]:
 # data are cleaning by the / lower_copy["payment method"]

In [693]:
lower_copy["payment method"].value_counts()

payment method
Digital Wallet    2291
Credit Card       2273
Cash              2258
ERROR              306
UNKNOWN            293
Name: count, dtype: int64

In [694]:
lower_copy["payment method"]=lower_copy["payment method"].str.replace("ERROR","NO_payment")

In [695]:
lower_copy["payment method"]=lower_copy["payment method"].str.replace("UNKNOWN","Cash")

In [696]:
print((2291+2273+2551+306)/4)

1855.25

In [697]:
lower_copy["payment method"]=lower_copy["payment method"].fillna("Credit Card")

In [698]:
lower_copy["payment method"].isnull().sum()

np.int64(0)

In [699]:
type(lower_copy["payment method"][98])

str

In [700]:
lower_copy["payment method"]=lower_copy["payment method"].astype=(int)

In [701]:
lower_copy.isnull().sum()

transaction id         0
item                   0
quantity               0
price per unit         0
total spent            0
payment method         0
location            3265
transaction date     159
dtype: int64

In [702]:
# know i am koring in the the columns name lower_copy["location"]

In [703]:
lower_copy["location"].value_counts()

In [707]:
print((3022+3017)/2)

3019.5

In [708]:
lower_copy["location"].isnull().sum()

np.int64(3265)

In [709]:
lower_copy["location"]=lower_copy["location"].str.replace("UNKNOWN","In-store")

In [713]:
lower_copy["location"].value_counts()

location
In-store    3355
Takeaway    3022
ERROR        358
Name: count, dtype: int64

In [714]:
lower_copy["location"]=lower_copy["location"].str.replace("ERROR","In-store")

In [715]:
lower_copy["location"].value_counts()

location
In-store    3713
Takeaway    3022
Name: count, dtype: int64

In [716]:
print((3713+3022)/2)

3367.5

In [718]:
lower_copy["location"]=lower_copy["location"].fillna("Takeaway")

In [720]:
lower_copy.isnull().sum()

transaction id        0
item                  0
quantity              0
price per unit        0
total spent           0
payment method        0
location              0
transaction date    159
dtype: int64

In [ ]:
# know is the working in the lower_copy["transaction date"]

In [727]:
lower_copy["transaction date"].isnull().sum()

np.int64(159)

In [731]:

lower_copy["transaction date"] = lower_copy["transaction date"].fillna(method="ffill")

/var/folders/m5/pjzzzf8n62x495_tfwb87yrh0000gn/T/ipykernel_61898/2529941395.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  lower_copy["transaction date"] = lower_copy["transaction date"].fillna(method="ffill")

In [732]:
lower_copy["transaction date"].isnull().sum()

np.int64(0)

In [770]:
print((lower_copy["transaction date"].value_counts()).mean())

27.3224043715847

In [763]:
lower_copy["transaction date"].value_counts()

transaction date
UNKNOWN       160
ERROR         144
2023-06-16     41
2023-07-21     40
2023-09-21     40
             ...
2023-09-24     15
2023-04-27     15
2023-07-30     15
2023-03-11     14
2023-02-17     14
Name: count, Length: 367, dtype: int64

In [767]:
lower_copy["transaction date"].value_counts().iloc[145:180]

transaction date
2023-09-15    28
2023-12-21    28
2023-06-09    27
2023-02-24    27
2023-10-23    27
2023-04-01    27
2023-05-08    27
2023-11-20    27
2023-02-01    27
2023-06-08    27
2023-09-05    27
2023-01-08    27
2023-11-04    27
2023-11-15    27
2023-10-03    27
2023-11-03    27
2023-03-20    27
2023-05-31    27
2023-03-24    27
2023-04-10    27
2023-01-21    27
2023-07-31    27
2023-05-04    27
2023-02-03    27
2023-12-30    27
2023-12-02    27
2023-07-15    27
2023-11-09    27
2023-01-16    27
2023-03-06    27
2023-09-09    27
2023-02-18    27
2023-01-04    27
2023-02-05    26
2023-07-19    26
Name: count, dtype: int64

In [768]:
lower_copy["transaction date"]=lower_copy["transaction date"].str.replace("UNKNOWN","2023-11-20")

In [769]:
lower_copy["transaction date"].value_counts()

transaction date
2023-11-20    187
ERROR         144
2023-06-16     41
2023-09-21     40
2023-02-06     40
             ...
2023-09-24     15
2023-11-24     15
2023-07-30     15
2023-03-11     14
2023-02-17     14
Name: count, Length: 366, dtype: int64

In [775]:
lower_copy["transaction date"]=lower_copy["transaction date"].str.replace("22023-11-03","2023-11-03")

In [776]:
lower_copy["transaction date"].value_counts()

transaction date
2023-11-20    187
2023-11-03    171
2023-06-16     41
2023-09-21     40
2023-07-21     40
             ...
2023-09-24     15
2023-11-24     15
2023-07-30     15
2023-03-11     14
2023-02-17     14
Name: count, Length: 365, dtype: int64

In [777]:
lower_copy["transaction date"].isnull().sum()

np.int64(0)

In [778]:
lower_copy.isnull().sum()

transaction id      0
item                0
quantity            0
price per unit      0
total spent         0
payment method      0
location            0
transaction date    0
dtype: int64

In [ ]:
# fillnaly clean the data(null,error,unkown)

In [780]:
lower_copy.to_csv("after_cleaning_data_sales.csv")