In [211]:
import numpy as np
import pandas as pd
import matplotlib as plt
data=pd.read_csv("A1(before_cleaning)_Expanded_data_with_more_features (1).csv")

In [212]:
data.head()

,Unnamed: 0,Gender,EthnicGroup,ParentEduc,LunchType,TestPrep,ParentMaritalStatus,PracticeSport,IsFirstChild,NrSiblings,TransportMeans,WklyStudyHours,MathScore,ReadingScore,WritingScore
0,0,female,NaN,bachelor's degree,standard,none,married,regularly,yes,3.0,school_bus,< 5,71,71,74
1,1,female,group C,some college,standard,NaN,married,sometimes,yes,0.0,NaN,5 - 10,69,90,88
2,2,female,group B,master's degree,standard,none,single,sometimes,yes,4.0,school_bus,< 5,87,93,91
3,3,male,group A,associate's degree,free/reduced,none,married,never,no,1.0,NaN,5 - 10,45,56,42
4,4,male,group C,some college,standard,none,married,sometimes,yes,0.0,school_bus,5 - 10,76,78,75

In [213]:
data.tail()

,Unnamed: 0,Gender,EthnicGroup,ParentEduc,LunchType,TestPrep,ParentMaritalStatus,PracticeSport,IsFirstChild,NrSiblings,TransportMeans,WklyStudyHours,MathScore,ReadingScore,WritingScore
30636,816,female,group D,high school,standard,none,single,sometimes,no,2.0,school_bus,5 - 10,59,61,65
30637,890,male,group E,high school,standard,none,single,regularly,no,1.0,private,5 - 10,58,53,51
30638,911,female,NaN,high school,free/reduced,completed,married,sometimes,no,1.0,private,5 - 10,61,70,67
30639,934,female,group D,associate's degree,standard,completed,married,regularly,no,3.0,school_bus,5 - 10,82,90,93
30640,960,male,group B,some college,standard,none,married,never,no,1.0,school_bus,5 - 10,64,60,58

In [214]:
 # first columns name is the removed data["	Unnamed: 0"]

In [215]:
data.drop(columns="Unnamed: 0",inplace=True)

In [216]:
data.columns 
data.shape

(30641, 14)

In [217]:
data.isnull().sum()

Gender                    0
EthnicGroup            1840
ParentEduc             1845
LunchType                 0
TestPrep               1830
ParentMaritalStatus    1190
PracticeSport           631
IsFirstChild            904
NrSiblings             1572
TransportMeans         3134
WklyStudyHours          955
MathScore                 0
ReadingScore              0
WritingScore              0
dtype: int64

In [218]:
data.duplicated().sum() # no duplicate value present in the null value in the columns

np.int64(0)

In [219]:
data.columns  # the columns name convert into the the lower case

Index(['Gender', 'EthnicGroup', 'ParentEduc', 'LunchType', 'TestPrep',
       'ParentMaritalStatus', 'PracticeSport', 'IsFirstChild', 'NrSiblings',
       'TransportMeans', 'WklyStudyHours', 'MathScore', 'ReadingScore',
       'WritingScore'],
      dtype='object')

In [220]:
new_columns=[]
for i in data.columns:
    new_columns.append(i.lower())
new_columns

['gender',
 'ethnicgroup',
 'parenteduc',
 'lunchtype',
 'testprep',
 'parentmaritalstatus',
 'practicesport',
 'isfirstchild',
 'nrsiblings',
 'transportmeans',
 'wklystudyhours',
 'mathscore',
 'readingscore',
 'writingscore']

In [221]:
data1=data.copy()

In [222]:
data1.column=new_columns

/var/folders/m5/pjzzzf8n62x495_tfwb87yrh0000gn/T/ipykernel_13327/2717124350.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  data1.column=new_columns

In [223]:
data1.columns

Index(['Gender', 'EthnicGroup', 'ParentEduc', 'LunchType', 'TestPrep',
       'ParentMaritalStatus', 'PracticeSport', 'IsFirstChild', 'NrSiblings',
       'TransportMeans', 'WklyStudyHours', 'MathScore', 'ReadingScore',
       'WritingScore'],
      dtype='object')

In [224]:
data1.rename(columns={"EthnicGroup":"Ethnic_Group"},inplace=True)

In [225]:
data1.rename(columns={'ParentEduc':'Parent_Educ', 'LunchType':'Lunch_Type', 'TestPrep':'Test_Prep',
       'ParentMaritalStatus':'Parent_Marital_Status', 'PracticeSport':'Practice_Sport', 'IsFirstChild':'Is_First_Child', 'NrSiblings':'Nr_Siblings',
       'TransportMeans':'Transport_Means', 'WklyStudyHours':'Wkly_Study_Hours', 'MathScore':'Math_Score', 'ReadingScore':'Reading_Score',
       'WritingScore':'Writing_Score'},inplace=True)

In [226]:
data.columns

Index(['Gender', 'EthnicGroup', 'ParentEduc', 'LunchType', 'TestPrep',
       'ParentMaritalStatus', 'PracticeSport', 'IsFirstChild', 'NrSiblings',
       'TransportMeans', 'WklyStudyHours', 'MathScore', 'ReadingScore',
       'WritingScore'],
      dtype='object')

In [227]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30641 entries, 0 to 30640
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Gender               30641 non-null  object
 1   EthnicGroup          28801 non-null  object
 2   ParentEduc           28796 non-null  object
 3   LunchType            30641 non-null  object
 4   TestPrep             28811 non-null  object
 5   ParentMaritalStatus  29451 non-null  object
 6   PracticeSport        30010 non-null  object
 7   IsFirstChild         29737 non-null  object
 8   NrSiblings           29069 non-null  float64
 9   TransportMeans       27507 non-null  object
 10  WklyStudyHours       29686 non-null  object
 11  MathScore            30641 non-null  int64
 12  ReadingScore         30641 non-null  int64
 13  WritingScore         30641 non-null  int64
dtypes: float64(1), int64(3), object(10)
memory usage: 3.3+ MB

In [228]:
data1.isnull().sum()

Gender                      0
Ethnic_Group             1840
Parent_Educ              1845
Lunch_Type                  0
Test_Prep                1830
Parent_Marital_Status    1190
Practice_Sport            631
Is_First_Child            904
Nr_Siblings              1572
Transport_Means          3134
Wkly_Study_Hours          955
Math_Score                  0
Reading_Score               0
Writing_Score               0
dtype: int64

In [229]:
# know i am working in the columns data1["Ethnic_Group"]

In [230]:
data1["Ethnic_Group"].value_counts()

Ethnic_Group
group C    9212
group D    7503
group B    5826
group E    4041
group A    2219
Name: count, dtype: int64

In [231]:
data1["Ethnic_Group"].isnull().sum()

np.int64(1840)

In [232]:
data1["Ethnic_Group"].isnull().sum()

np.int64(1840)

In [233]:
data1["Ethnic_Group"].value_counts()

Ethnic_Group
group C    9212
group D    7503
group B    5826
group E    4041
group A    2219
Name: count, dtype: int64

In [234]:
print(data1["Ethnic_Group"].value_counts().mode())
print("mean")
print(data1["Ethnic_Group"].value_counts().mean())

0    2219
1    4041
2    5826
3    7503
4    9212
Name: count, dtype: int64
mean
5760.2

In [235]:
#data1["Ethnic_Group"]=data1["Ethnic_Group"].fillna(data1["Ethnic_Group"].mean()[0])

data1["Ethnic_Group"] = data1["Ethnic_Group"].fillna(data1["Ethnic_Group"].mode()[0])

In [236]:
data1["Ethnic_Group"].value_counts()

Ethnic_Group
group C    11052
group D     7503
group B     5826
group E     4041
group A     2219
Name: count, dtype: int64

In [237]:
data1.isnull().sum()

Gender                      0
Ethnic_Group                0
Parent_Educ              1845
Lunch_Type                  0
Test_Prep                1830
Parent_Marital_Status    1190
Practice_Sport            631
Is_First_Child            904
Nr_Siblings              1572
Transport_Means          3134
Wkly_Study_Hours          955
Math_Score                  0
Reading_Score               0
Writing_Score               0
dtype: int64

In [238]:
# now  i am working in the columns data1["Parent_Educ"]

In [239]:
data1["Parent_Educ"].value_counts()

Parent_Educ
some college          6633
high school           5687
associate's degree    5550
some high school      5517
bachelor's degree     3386
master's degree       2023
Name: count, dtype: int64

In [240]:
data1["Parent_Educ"].value_counts().mean()

np.float64(4799.333333333333)

In [241]:
data1["Parent_Educ"]=data1["Ethnic_Group"].fillna(data1["Ethnic_Group"].mode()[0])

In [242]:
data1["Parent_Educ"].isnull().sum()

np.int64(0)

In [243]:
data1["Parent_Educ"].value_counts()

Parent_Educ
group C    11052
group D     7503
group B     5826
group E     4041
group A     2219
Name: count, dtype: int64

In [244]:
data1.isnull().sum()

Gender                      0
Ethnic_Group                0
Parent_Educ                 0
Lunch_Type                  0
Test_Prep                1830
Parent_Marital_Status    1190
Practice_Sport            631
Is_First_Child            904
Nr_Siblings              1572
Transport_Means          3134
Wkly_Study_Hours          955
Math_Score                  0
Reading_Score               0
Writing_Score               0
dtype: int64

In [245]:
# know i am working in the columns data1["Test_Prep"]

In [246]:
data1["Test_Prep"].isnull().sum()

np.int64(1830)

In [247]:
data1["Test_Prep"].value_counts()

Test_Prep
none         18856
completed     9955
Name: count, dtype: int64

In [248]:
data1["Test_Prep"].value_counts().mean()

np.float64(14405.5)

In [249]:
data1["Test_Prep"]=data1["Test_Prep"].fillna(data1["Test_Prep"].mode()[0])

In [250]:
data1["Test_Prep"].value_counts()

Test_Prep
none         20686
completed     9955
Name: count, dtype: int64

In [251]:
# # know i am working in the columns data1["Parent_Marital_Status"]

In [252]:
data1["Parent_Marital_Status"].value_counts()

Parent_Marital_Status
married     16844
single       7097
divorced     4919
widowed       591
Name: count, dtype: int64

In [253]:
data1["Parent_Marital_Status"].value_counts().mode()

0      591
1     4919
2     7097
3    16844
Name: count, dtype: int64

In [254]:
data1["Parent_Marital_Status"].value_counts().mean()

np.float64(7362.75)

In [255]:
data1["Parent_Marital_Status"]=data1["Parent_Marital_Status"].fillna(data1["Parent_Marital_Status"].mode()[0])

In [256]:
data1.isnull().sum()

Gender                      0
Ethnic_Group                0
Parent_Educ                 0
Lunch_Type                  0
Test_Prep                   0
Parent_Marital_Status       0
Practice_Sport            631
Is_First_Child            904
Nr_Siblings              1572
Transport_Means          3134
Wkly_Study_Hours          955
Math_Score                  0
Reading_Score               0
Writing_Score               0
dtype: int64

In [257]:
# # know i am working in the columns data1["Practice_Sport"]

In [258]:
data1["Practice_Sport"].value_counts()

Practice_Sport
sometimes    15213
regularly    10793
never         4004
Name: count, dtype: int64

In [259]:
print(data1["Practice_Sport"].value_counts().mean())
data1["Practice_Sport"].value_counts().mode()

10003.333333333334

0     4004
1    10793
2    15213
Name: count, dtype: int64

In [260]:
data1["Practice_Sport"]=data1["Practice_Sport"].fillna(data1["Practice_Sport"].mode()[0])

In [261]:
data1.isnull().sum()

Gender                      0
Ethnic_Group                0
Parent_Educ                 0
Lunch_Type                  0
Test_Prep                   0
Parent_Marital_Status       0
Practice_Sport              0
Is_First_Child            904
Nr_Siblings              1572
Transport_Means          3134
Wkly_Study_Hours          955
Math_Score                  0
Reading_Score               0
Writing_Score               0
dtype: int64

In [262]:
# # know i am working in the columns data1["Is_First_Child"]
data1["Is_First_Child"].value_counts()

Is_First_Child
yes    19082
no     10655
Name: count, dtype: int64

In [263]:
data1["Is_First_Child"].value_counts().mean()

np.float64(14868.5)

In [264]:
data1["Is_First_Child"].value_counts().mode()

0    10655
1    19082
Name: count, dtype: int64

In [265]:
data1["Is_First_Child"]=data1["Is_First_Child"].fillna(data1["Is_First_Child"].mode()[0])

In [266]:
data1.isnull().sum()

Gender                      0
Ethnic_Group                0
Parent_Educ                 0
Lunch_Type                  0
Test_Prep                   0
Parent_Marital_Status       0
Practice_Sport              0
Is_First_Child              0
Nr_Siblings              1572
Transport_Means          3134
Wkly_Study_Hours          955
Math_Score                  0
Reading_Score               0
Writing_Score               0
dtype: int64

In [267]:
# # know i am working in the columns data1["Nr_Siblings"]

In [268]:
data1["Nr_Siblings"].value_counts()

Nr_Siblings
1.0    8217
2.0    6790
3.0    6123
0.0    3085
4.0    2941
5.0    1320
6.0     302
7.0     291
Name: count, dtype: int64

In [269]:
data1["Nr_Siblings"].value_counts().mean()

np.float64(3633.625)

In [270]:
data1["Nr_Siblings"].value_counts().mode()

0     291
1     302
2    1320
3    2941
4    3085
5    6123
6    6790
7    8217
Name: count, dtype: int64

In [271]:
data1["Nr_Siblings"].isnull().sum()

np.int64(1572)

In [272]:
data1["Nr_Siblings"]=data1["Nr_Siblings"].fillna(data1["Nr_Siblings"].mean())

In [273]:
data1["Nr_Siblings"].value_counts()

Nr_Siblings
1.000000    8217
2.000000    6790
3.000000    6123
0.000000    3085
4.000000    2941
2.145894    1572
5.000000    1320
6.000000     302
7.000000     291
Name: count, dtype: int64

In [274]:
data1["Nr_Siblings"].isnull().sum()

np.int64(0)

In [275]:
# convert the data type
type(data1["Nr_Siblings"][7])

numpy.float64

In [276]:
 #to covert into the int type So in the

In [277]:
data1["Nr_Siblings"]=data1["Nr_Siblings"].astype(int)

In [278]:
data1["Nr_Siblings"].value_counts()

Nr_Siblings
2    8362
1    8217
3    6123
0    3085
4    2941
5    1320
6     302
7     291
Name: count, dtype: int64

In [279]:
# convert the data type
type(data1["Nr_Siblings"][7])

numpy.int64

In [280]:
data1.isnull().sum()

Gender                      0
Ethnic_Group                0
Parent_Educ                 0
Lunch_Type                  0
Test_Prep                   0
Parent_Marital_Status       0
Practice_Sport              0
Is_First_Child              0
Nr_Siblings                 0
Transport_Means          3134
Wkly_Study_Hours          955
Math_Score                  0
Reading_Score               0
Writing_Score               0
dtype: int64

In [281]:
# # know i am working in the columns data1["Transport_Means"]

In [282]:
data1["Transport_Means"].isnull().sum()

np.int64(3134)

In [283]:
data1["Transport_Means"].value_counts()

Transport_Means
school_bus    16145
private       11362
Name: count, dtype: int64

In [284]:
data1["Transport_Means"]=data1["Transport_Means"].fillna(data1["Transport_Means"].mode()[0])

In [285]:
data1["Transport_Means"].value_counts()

Transport_Means
school_bus    19279
private       11362
Name: count, dtype: int64

In [286]:
data1.isnull().sum()

Gender                     0
Ethnic_Group               0
Parent_Educ                0
Lunch_Type                 0
Test_Prep                  0
Parent_Marital_Status      0
Practice_Sport             0
Is_First_Child             0
Nr_Siblings                0
Transport_Means            0
Wkly_Study_Hours         955
Math_Score                 0
Reading_Score              0
Writing_Score              0
dtype: int64

In [287]:
# # know i am working in the columns data1["Wkly_Study_Hours"]

In [288]:
data1["Wkly_Study_Hours"].isnull().sum()

np.int64(955)

In [289]:
data1["Wkly_Study_Hours"].value_counts()

Wkly_Study_Hours
5 - 10    16246
< 5        8238
> 10       5202
Name: count, dtype: int64

In [290]:
type(data1["Wkly_Study_Hours"][8])

str

In [291]:
data1["Wkly_Study_Hours"]=data1["Wkly_Study_Hours"].fillna(data1["Wkly_Study_Hours"].mode()[0])

In [292]:
data1.isnull().sum()

Gender                   0
Ethnic_Group             0
Parent_Educ              0
Lunch_Type               0
Test_Prep                0
Parent_Marital_Status    0
Practice_Sport           0
Is_First_Child           0
Nr_Siblings              0
Transport_Means          0
Wkly_Study_Hours         0
Math_Score               0
Reading_Score            0
Writing_Score            0
dtype: int64

In [293]:
data1.head(30)

,Gender,Ethnic_Group,Parent_Educ,Lunch_Type,Test_Prep,Parent_Marital_Status,Practice_Sport,Is_First_Child,Nr_Siblings,Transport_Means,Wkly_Study_Hours,Math_Score,Reading_Score,Writing_Score
0,female,group C,group C,standard,none,married,regularly,yes,3,school_bus,< 5,71,71,74
1,female,group C,group C,standard,none,married,sometimes,yes,0,school_bus,5 - 10,69,90,88
2,female,group B,group B,standard,none,single,sometimes,yes,4,school_bus,< 5,87,93,91
3,male,group A,group A,free/reduced,none,married,never,no,1,school_bus,5 - 10,45,56,42
4,male,group C,group C,standard,none,married,sometimes,yes,0,school_bus,5 - 10,76,78,75
5,female,group B,group B,standard,none,married,regularly,yes,1,school_bus,5 - 10,73,84,79
6,female,group B,group B,standard,completed,widowed,never,no,1,private,5 - 10,85,93,89
7,male,group B,group B,free/reduced,none,married,sometimes,yes,1,private,> 10,41,43,39
8,male,group D,group D,free/reduced,completed,single,sometimes,no,3,private,> 10,65,64,68
9,female,group B,group B,free/reduced,none,married,regularly,yes,2,private,< 5,37,59,50
10,male,group C,group C,standard,none,married,sometimes,yes,1,private,5 - 10,58,54,52
11,male,group D,group D,standard,none,divorced,sometimes,yes,1,school_bus,5 - 10,40,52,43
12,female,group B,group B,standard,none,married,regularly,no,1,private,5 - 10,66,82,74
13,male,group A,group A,standard,completed,single,sometimes,yes,1,private,> 10,80,73,71
14,female,group A,group A,standard,none,divorced,sometimes,yes,2,private,< 5,48,53,58
15,female,group C,group C,standard,none,married,sometimes,yes,0,private,5 - 10,69,75,78
16,male,group C,group C,standard,none,married,sometimes,yes,0,school_bus,5 - 10,88,89,86
17,female,group B,group B,free/reduced,none,divorced,sometimes,yes,1,school_bus,5 - 10,18,32,28
18,male,group C,group C,free/reduced,completed,single,sometimes,no,1,private,5 - 10,46,42,47
19,female,group C,group C,free/reduced,none,married,never,yes,3,private,< 5,50,56,58
20,male,group D,group D,standard,none,married,sometimes,yes,5,school_bus,5 - 10,66,69,63
21,female,group B,group B,free/reduced,completed,married,sometimes,no,2,school_bus,5 - 10,65,75,70
22,male,group D,group D,standard,none,married,never,yes,5,school_bus,5 - 10,42,53,51
23,female,group C,group C,standard,none,divorced,never,no,3,school_bus,5 - 10,66,71,71
24,male,group D,group D,free/reduced,completed,married,sometimes,yes,2,school_bus,5 - 10,74,71,80
25,male,group A,group A,free/reduced,none,married,regularly,yes,1,school_bus,5 - 10,75,76,76
26,male,group B,group B,standard,none,married,sometimes,yes,5,school_bus,< 5,66,53,53
27,female,group C,group C,standard,none,married,sometimes,yes,4,school_bus,> 10,69,70,76
28,male,group C,group C,standard,none,married,sometimes,no,1,private,5 - 10,70,70,65
29,female,group D,group D,standard,none,single,sometimes,yes,0,private,< 5,66,72,72

In [296]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30641 entries, 0 to 30640
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Gender                 30641 non-null  object
 1   Ethnic_Group           30641 non-null  object
 2   Parent_Educ            30641 non-null  object
 3   Lunch_Type             30641 non-null  object
 4   Test_Prep              30641 non-null  object
 5   Parent_Marital_Status  30641 non-null  object
 6   Practice_Sport         30641 non-null  object
 7   Is_First_Child         30641 non-null  object
 8   Nr_Siblings            30641 non-null  int64
 9   Transport_Means        30641 non-null  object
 10  Wkly_Study_Hours       30641 non-null  object
 11  Math_Score             30641 non-null  int64
 12  Reading_Score          30641 non-null  int64
 13  Writing_Score          30641 non-null  int64
dtypes: int64(4), object(10)
memory usage: 3.3+ MB

In [ ]:
# to. fillter dataset 
data1.to_csv("",index=Fa)