In [62]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [63]:
data=pd.read_csv("A2_(beafore_cleanig)Titanic-Dataset.csv")

In [64]:
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [65]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [66]:
data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [67]:
data.duplicated().sum() # the duplicate value not present in the data set

np.int64(0)

In [68]:
# the two columns name is the diffirent thats why  same column name change
data.rename(columns={'PassengerId':'Passenger_Id','SibSp':'Sib_Sp','Pclass':'P_class'},inplace=True)

In [69]:
data.columns

Index(['Passenger_Id', 'Survived', 'P_class', 'Name', 'Sex', 'Age', 'Sib_Sp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [70]:
# the columns name upper case
# so
new_column=[]
for i in data.columns:
    new_column.append(i.upper())
new_column

['PASSENGER_ID',
 'SURVIVED',
 'P_CLASS',
 'NAME',
 'SEX',
 'AGE',
 'SIB_SP',
 'PARCH',
 'TICKET',
 'FARE',
 'CABIN',
 'EMBARKED']

In [71]:
data1=data.copy()

In [72]:
data1.columns=new_column

In [73]:
data1.columns # the columns name change easly

Index(['PASSENGER_ID', 'SURVIVED', 'P_CLASS', 'NAME', 'SEX', 'AGE', 'SIB_SP',
       'PARCH', 'TICKET', 'FARE', 'CABIN', 'EMBARKED'],
      dtype='object')

In [74]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PASSENGER_ID  891 non-null    int64
 1   SURVIVED      891 non-null    int64
 2   P_CLASS       891 non-null    int64
 3   NAME          891 non-null    object
 4   SEX           891 non-null    object
 5   AGE           714 non-null    float64
 6   SIB_SP        891 non-null    int64
 7   PARCH         891 non-null    int64
 8   TICKET        891 non-null    object
 9   FARE          891 non-null    float64
 10  CABIN         204 non-null    object
 11  EMBARKED      889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [75]:
data1.isnull().sum() # now cheak one by one columns and cleaning the data

PASSENGER_ID      0
SURVIVED          0
P_CLASS           0
NAME              0
SEX               0
AGE             177
SIB_SP            0
PARCH             0
TICKET            0
FARE              0
CABIN           687
EMBARKED          2
dtype: int64

In [76]:
# first type conver in the columns
data1["PASSENGER_ID"]=data1["PASSENGER_ID"].astype(str)

In [77]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PASSENGER_ID  891 non-null    object
 1   SURVIVED      891 non-null    int64
 2   P_CLASS       891 non-null    int64
 3   NAME          891 non-null    object
 4   SEX           891 non-null    object
 5   AGE           714 non-null    float64
 6   SIB_SP        891 non-null    int64
 7   PARCH         891 non-null    int64
 8   TICKET        891 non-null    object
 9   FARE          891 non-null    float64
 10  CABIN         204 non-null    object
 11  EMBARKED      889 non-null    object
dtypes: float64(2), int64(4), object(6)
memory usage: 83.7+ KB

In [78]:
# for i in range(1,len(data1)+1):
#     if(i<=9):
#         data1["PASSENGER_ID"]=["0501MG23100"+ str(i) for i in range(1,len(data1)+1)]
#     else:
#         data1["PASSENGER_ID"]=["0501MG2310"+ str(i) for i in range(1,len(data1)+1)]
data1["PASSENGER_ID"] = [f"0501MG2310{i:02d}" for i in range(1, len(data1) + 1)
]

In [79]:

#data1["PASSENGER_ID"] = ["0101AD2310" + str(i) for i in range(1, len(data1) + 1)]

In [80]:

data1["PASSENGER_ID"]

0       0501MG231001
1       0501MG231002
2       0501MG231003
3       0501MG231004
4       0501MG231005
           ...
886    0501MG2310887
887    0501MG2310888
888    0501MG2310889
889    0501MG2310890
890    0501MG2310891
Name: PASSENGER_ID, Length: 891, dtype: object

In [81]:
data1

,PASSENGER_ID,SURVIVED,P_CLASS,NAME,SEX,AGE,SIB_SP,PARCH,TICKET,FARE,CABIN,EMBARKED
0,0501MG231001,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,0501MG231002,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,0501MG231003,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,0501MG231004,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,0501MG231005,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,0501MG2310887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,0501MG2310888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,0501MG2310889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,0501MG2310890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,0501MG2310891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [82]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PASSENGER_ID  891 non-null    object
 1   SURVIVED      891 non-null    int64
 2   P_CLASS       891 non-null    int64
 3   NAME          891 non-null    object
 4   SEX           891 non-null    object
 5   AGE           714 non-null    float64
 6   SIB_SP        891 non-null    int64
 7   PARCH         891 non-null    int64
 8   TICKET        891 non-null    object
 9   FARE          891 non-null    float64
 10  CABIN         204 non-null    object
 11  EMBARKED      889 non-null    object
dtypes: float64(2), int64(4), object(6)
memory usage: 83.7+ KB

In [83]:
# now i am working in the columns in the

In [84]:
data1["SURVIVED"].value_counts() # mean thats ok the columns

SURVIVED
0    549
1    342
Name: count, dtype: int64

In [85]:
data1["P_CLASS"].value_counts()

P_CLASS
3    491
1    216
2    184
Name: count, dtype: int64

In [86]:
data1["NAME"]

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: NAME, Length: 891, dtype: object

In [87]:
data1["NAME"].isnull().sum()

np.int64(0)

In [88]:
data1["NAME"].value_counts()

NAME
Dooley, Mr. Patrick                                    1
Braund, Mr. Owen Harris                                1
Cumings, Mrs. John Bradley (Florence Briggs Thayer)    1
Heikkinen, Miss. Laina                                 1
Futrelle, Mrs. Jacques Heath (Lily May Peel)           1
                                                      ..
Hewlett, Mrs. (Mary D Kingcome)                        1
Vestrom, Miss. Hulda Amanda Adolfina                   1
Andersson, Mr. Anders Johan                            1
Saundercock, Mr. William Henry                         1
Bonnell, Miss. Elizabeth                               1
Name: count, Length: 891, dtype: int64

In [89]:
 # know i am workin the columns  data1["AGE"]

In [90]:
data1["AGE"]

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: AGE, Length: 891, dtype: float64

In [91]:
data1["AGE"].value_counts().median()

np.float64(5.0)

In [92]:
data1["AGE"]=data1["AGE"].fillna(data1["AGE"].median())

In [93]:
data1["AGE"] # and then to convert the data type in the columns 
#folat data type convert into the int # beace the age alwge in the int type

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888    28.0
889    26.0
890    32.0
Name: AGE, Length: 891, dtype: float64

In [94]:
data1["AGE"]=data1["AGE"].astype(int)

In [95]:
data1["AGE"]

0      22
1      38
2      26
3      35
4      35
       ..
886    27
887    19
888    28
889    26
890    32
Name: AGE, Length: 891, dtype: int64

In [96]:
 # now i am working in the columns in the 
# 6   SIB_SP        891 non-null    int64

In [97]:
data1["SIB_SP"].value_counts()

SIB_SP
0    608
1    209
2     28
4     18
3     16
8      7
5      5
Name: count, dtype: int64

In [98]:
data1["SIB_SP"].isnull().sum()

np.int64(0)

In [99]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PASSENGER_ID  891 non-null    object
 1   SURVIVED      891 non-null    int64
 2   P_CLASS       891 non-null    int64
 3   NAME          891 non-null    object
 4   SEX           891 non-null    object
 5   AGE           891 non-null    int64
 6   SIB_SP        891 non-null    int64
 7   PARCH         891 non-null    int64
 8   TICKET        891 non-null    object
 9   FARE          891 non-null    float64
 10  CABIN         204 non-null    object
 11  EMBARKED      889 non-null    object
dtypes: float64(1), int64(5), object(6)
memory usage: 83.7+ KB

In [100]:
# 10  CABIN         204 non-null    object

In [101]:
data1["CABIN"] # its columns drop beacuse only 40% dataset present that'why

0       NaN
1       C85
2       NaN
3      C123
4       NaN
       ...
886     NaN
887     B42
888     NaN
889    C148
890     NaN
Name: CABIN, Length: 891, dtype: object

In [102]:
data1["CABIN"].value_counts()

CABIN
G6             4
C23 C25 C27    4
B96 B98        4
F2             3
D              3
              ..
E17            1
A24            1
C50            1
B42            1
C148           1
Name: count, Length: 147, dtype: int64

In [103]:
data1["CABIN"].value_counts().median()

np.float64(1.0)

In [104]:
data1.drop(columns={"CABIN"},inplace=True)

In [105]:
data1.columns

Index(['PASSENGER_ID', 'SURVIVED', 'P_CLASS', 'NAME', 'SEX', 'AGE', 'SIB_SP',
       'PARCH', 'TICKET', 'FARE', 'EMBARKED'],
      dtype='object')

In [106]:
#now i working in the columns name=data1["EMBARKED"]

In [107]:
data1["EMBARKED"]

0      S
1      C
2      S
3      S
4      S
      ..
886    S
887    S
888    S
889    C
890    Q
Name: EMBARKED, Length: 891, dtype: object

In [108]:
data1["EMBARKED"].value_counts()

EMBARKED
S    644
C    168
Q     77
Name: count, dtype: int64

In [109]:
data1["EMBARKED"].value_counts().mode()

0     77
1    168
2    644
Name: count, dtype: int64

In [110]:
data1["EMBARKED"]=data1["EMBARKED"].fillna(data1["EMBARKED"].mode())

In [111]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PASSENGER_ID  891 non-null    object
 1   SURVIVED      891 non-null    int64
 2   P_CLASS       891 non-null    int64
 3   NAME          891 non-null    object
 4   SEX           891 non-null    object
 5   AGE           891 non-null    int64
 6   SIB_SP        891 non-null    int64
 7   PARCH         891 non-null    int64
 8   TICKET        891 non-null    object
 9   FARE          891 non-null    float64
 10  EMBARKED      889 non-null    object
dtypes: float64(1), int64(5), object(5)
memory usage: 76.7+ KB

In [112]:
data1.to_csv("A2_(After_cleanig)Titanic-Dataset.csv",index=False)