In [350]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt

In [351]:
data=pd.read_csv("A3_(before_cleaning)dirty_customer_dataset_1000.csv")

In [352]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         1020 non-null   object
 1   Name                975 non-null    object
 2   Gender              747 non-null    object
 3   Age                 760 non-null    object
 4   City                852 non-null    object
 5   Signup_Date         1020 non-null   object
 6   Last_Purchase_Date  923 non-null    object
 7   Purchase_Amount     679 non-null    object
 8   Feedback_Score      861 non-null    float64
 9   Email               1020 non-null   object
 10  Phone_Number        1020 non-null   object
 11  Country             826 non-null    object
dtypes: float64(1), object(11)
memory usage: 95.8+ KB

In [353]:
data

,Customer_ID,Name,Gender,Age,City,Signup_Date,Last_Purchase_Date,Purchase_Amount,Feedback_Score,Email,Phone_Number,Country
0,CUST0001,Luke Hanson,NaN,28,Chennai,2023-11-11,2026-02-21,₹11040,1.0,kevinfisher@hotmail.com,316.314.2031,NaN
1,CUST0002,Lisa Costa,Other,NaN,Pune,2026-04-06,2026-04-18,₹15142,1.0,davidrobinson@kelly-crawford.net,(600)176-5674x84235,USA
2,CUST0003,Mr. Kevin Gamble,Female,33 yrs,NaN,2021-08-26,2026-04-18,NaN,NaN,wrong_email.com,+1-322-053-8016x2164,India
3,CUST0004,Jennifer Santos,NaN,60 yrs,NaN,2025-04-01,2025-12-18,26072,5.0,wrong_email.com,260.082.5758x91945,Canada
4,CUST0005,NaN,NaN,Age is 45 years,NaN,2024-09-08,2025-10-02,NaN,5.0,sancheztina@brooks.com,+1-609-632-0152,UK
...,...,...,...,...,...,...,...,...,...,...,...,...
1015,CUST0016,Carrie Thompson,Other,27 yrs,Indore,2023-05-06,2025-01-13,12485,5.0,samantharobinson@christian.com,546-721-9533,NaN
1016,CUST0017,James Hatfield Jr.,NaN,NaN,Pune,2022-08-02,2026-04-06,₹34111,1.0,mistybaker@smith.com,943-766-3014x257,India
1017,CUST0018,Alicia Williams,Other,NaN,Delhi,2023-09-27,2024-07-31,₹25641,4.0,justin15@yahoo.com,239-015-0306,India
1018,CUST0019,Duane Oconnell,NaN,NaN,Indore,2023-09-13,2025-06-24,41419,5.0,uwatson@boyd.net,903-570-3269,Canada
1019,CUST0020,Jonathan Monroe,Female,NaN,Bhopal,2021-06-01,2024-06-06,₹35910,NaN,shawnchavez@hotmail.com,408.015.9136,Canada

In [354]:
data.duplicated().sum() # first of all remove the duplicate value of the data

np.int64(20)

In [355]:
data.drop_duplicates(inplace=True)

In [356]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         1000 non-null   object
 1   Name                956 non-null    object
 2   Gender              735 non-null    object
 3   Age                 750 non-null    object
 4   City                835 non-null    object
 5   Signup_Date         1000 non-null   object
 6   Last_Purchase_Date  904 non-null    object
 7   Purchase_Amount     666 non-null    object
 8   Feedback_Score      845 non-null    float64
 9   Email               1000 non-null   object
 10  Phone_Number        1000 non-null   object
 11  Country             809 non-null    object
dtypes: float64(1), object(11)
memory usage: 101.6+ KB

In [357]:
 # now i am working in the columns in the data["Name"]

In [358]:
data["Name"].value_counts().mode()

0    1
Name: count, dtype: int64

In [359]:
data["Name"]=data["Name"].fillna(data["Name"].mode()[0])

In [360]:
 # now i am working in the columns in the data["Gender"]

In [361]:
data["Gender"].value_counts()

Gender
Female    248
Other     247
Male      240
Name: count, dtype: int64

In [362]:
data["Gender"].value_counts().mode()

0    240
1    247
2    248
Name: count, dtype: int64

In [363]:
data["Gender"]=data["Gender"].fillna(data["Gender"].mode()[0])

In [364]:
data["Gender"].isnull().sum()

np.int64(0)

In [365]:
data.isnull().sum()

Customer_ID             0
Name                    0
Gender                  0
Age                   250
City                  165
Signup_Date             0
Last_Purchase_Date     96
Purchase_Amount       334
Feedback_Score        155
Email                   0
Phone_Number            0
Country               191
dtype: int64

In [366]:
 # now i am working in the columns in the data["Age"]

In [367]:
data["Age"]

0                   28
1                  NaN
2               33 yrs
3               60 yrs
4      Age is 45 years
            ...
995                 57
996                NaN
997    Age is 22 years
998    Age is 47 years
999             39 yrs
Name: Age, Length: 1000, dtype: object

In [368]:
import re
def data_num(num):
    new_data=re.findall(r'[0-9]+',str(num))
    if(len(new_data)>0):
        return new_data[0]
    else:
        return np.nan

In [369]:
data["Age"]=data["Age"].apply(lambda x:data_num(x))

In [370]:
data["Age"]

0       28
1      NaN
2       33
3       60
4       45
      ...
995     57
996    NaN
997     22
998     47
999     39
Name: Age, Length: 1000, dtype: object

In [371]:
col=data["Age"]

In [372]:
col.isnull().sum()

np.int64(250)

In [373]:
a=col.dropna()

In [374]:
a.isnull().sum()

np.int64(0)

In [375]:
b=a.astype(int)

In [376]:
b.mean()
b.mode()

0    38
Name: Age, dtype: int64

In [377]:
data["Age"].value_counts()

Age
38    27
29    24
42    24
36    23
51    22
60    20
23    20
52    20
40    20
20    19
18    19
22    19
25    19
32    19
30    18
28    18
45    18
58    18
56    18
46    17
48    17
24    17
34    17
50    17
39    17
33    16
54    16
19    16
47    16
35    16
59    15
26    15
37    15
31    15
57    15
27    14
21    14
49    14
55    14
44    14
43    14
41    12
53    12
Name: count, dtype: int64

In [378]:
data["Age"]=data["Age"].fillna("38")

In [379]:
data["Age"].isnull().sum()

np.int64(0)

In [380]:
data["Age"]=data["Age"].astype(int)

In [381]:
data["Age"]

0      28
1      38
2      33
3      60
4      45
       ..
995    57
996    38
997    22
998    47
999    39
Name: Age, Length: 1000, dtype: int64

In [382]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         1000 non-null   object
 1   Name                1000 non-null   object
 2   Gender              1000 non-null   object
 3   Age                 1000 non-null   int64
 4   City                835 non-null    object
 5   Signup_Date         1000 non-null   object
 6   Last_Purchase_Date  904 non-null    object
 7   Purchase_Amount     666 non-null    object
 8   Feedback_Score      845 non-null    float64
 9   Email               1000 non-null   object
 10  Phone_Number        1000 non-null   object
 11  Country             809 non-null    object
dtypes: float64(1), int64(1), object(10)
memory usage: 101.6+ KB

In [383]:
# # now i am working in the columns in the data["Age"]

In [384]:
data["City"].isnull().sum()

np.int64(165)

In [385]:
data["City"].value_counts()

City
Pune       149
Indore     143
Mumbai     140
Delhi      136
Chennai    135
Bhopal     132
Name: count, dtype: int64

In [386]:
print(data["City"].value_counts().mode())
print(data["City"].value_counts().mean())

0    132
1    135
2    136
3    140
4    143
5    149
Name: count, dtype: int64
139.16666666666666

In [387]:
data["City"]=data["City"].fillna(data["City"].mode()[0])

In [388]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         1000 non-null   object
 1   Name                1000 non-null   object
 2   Gender              1000 non-null   object
 3   Age                 1000 non-null   int64
 4   City                1000 non-null   object
 5   Signup_Date         1000 non-null   object
 6   Last_Purchase_Date  904 non-null    object
 7   Purchase_Amount     666 non-null    object
 8   Feedback_Score      845 non-null    float64
 9   Email               1000 non-null   object
 10  Phone_Number        1000 non-null   object
 11  Country             809 non-null    object
dtypes: float64(1), int64(1), object(10)
memory usage: 101.6+ KB

In [389]:
data['Last_Purchase_Date']

0      2026-02-21
1      2026-04-18
2      2026-04-18
3      2025-12-18
4      2025-10-02
          ...
995    2024-09-18
996    2024-07-28
997    2025-09-15
998           NaN
999    2025-04-25
Name: Last_Purchase_Date, Length: 1000, dtype: object

In [390]:
data['Last_Purchase_Date']=data['Last_Purchase_Date'].fillna(method='ffill')

/var/folders/m5/pjzzzf8n62x495_tfwb87yrh0000gn/T/ipykernel_18586/1123752936.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data['Last_Purchase_Date']=data['Last_Purchase_Date'].fillna(method='ffill')

In [391]:
data['Last_Purchase_Date'].isnull().sum()

np.int64(0)

In [392]:
data['City'].value_counts().mode()

0    132
1    135
2    136
3    140
4    143
5    314
Name: count, dtype: int64

In [393]:
data.isnull().sum()

Customer_ID             0
Name                    0
Gender                  0
Age                     0
City                    0
Signup_Date             0
Last_Purchase_Date      0
Purchase_Amount       334
Feedback_Score        155
Email                   0
Phone_Number            0
Country               191
dtype: int64

In [394]:
data['Purchase_Amount'][0] # '₹11040' to remove the remove

'₹11040'

In [395]:
data['Purchase_Amount']=data['Purchase_Amount'].str.replace("₹","")

In [396]:
data['Purchase_Amount']

0      11040
1      15142
2        NaN
3      26072
4        NaN
       ...
995    34413
996    49247
997      NaN
998    48567
999      NaN
Name: Purchase_Amount, Length: 1000, dtype: object

In [397]:
df=data['Purchase_Amount'] #

In [398]:
df.dropna(inplace=True)

In [399]:
df.astype(int).mean()

np.float64(24496.75075075075)

In [400]:
df.astype(int).median()

np.float64(24248.5)

In [401]:
data['Purchase_Amount']=data['Purchase_Amount'].fillna("24248")

In [402]:
data['Purchase_Amount']=data['Purchase_Amount'].astype(int)

In [403]:
data['Purchase_Amount']

0      11040
1      15142
2      24248
3      26072
4      24248
       ...
995    34413
996    49247
997    24248
998    48567
999    24248
Name: Purchase_Amount, Length: 1000, dtype: int64

In [404]:
data.isnull().sum()

Customer_ID             0
Name                    0
Gender                  0
Age                     0
City                    0
Signup_Date             0
Last_Purchase_Date      0
Purchase_Amount         0
Feedback_Score        155
Email                   0
Phone_Number            0
Country               191
dtype: int64

In [405]:
data['Feedback_Score']

0      1.0
1      1.0
2      NaN
3      5.0
4      5.0
      ...
995    1.0
996    5.0
997    5.0
998    NaN
999    3.0
Name: Feedback_Score, Length: 1000, dtype: float64

In [406]:
data['Feedback_Score'].value_counts().median()

np.float64(169.0)

In [407]:
data['Feedback_Score']=data['Feedback_Score'].fillna(data['Feedback_Score'].median())

In [408]:
data.isnull().sum()

Customer_ID             0
Name                    0
Gender                  0
Age                     0
City                    0
Signup_Date             0
Last_Purchase_Date      0
Purchase_Amount         0
Feedback_Score          0
Email                   0
Phone_Number            0
Country               191
dtype: int64

In [409]:
data['Country'].isnull().sum()

np.int64(191)

In [410]:
data['Country'].value_counts().mode()

0    193
1    195
2    203
3    218
Name: count, dtype: int64

In [411]:
data['Country']=data['Country'].fillna(data['Country'].mode()[0])

In [412]:
data

,Customer_ID,Name,Gender,Age,City,Signup_Date,Last_Purchase_Date,Purchase_Amount,Feedback_Score,Email,Phone_Number,Country
0,CUST0001,Luke Hanson,Female,28,Chennai,2023-11-11,2026-02-21,11040,1.0,kevinfisher@hotmail.com,316.314.2031,Canada
1,CUST0002,Lisa Costa,Other,38,Pune,2026-04-06,2026-04-18,15142,1.0,davidrobinson@kelly-crawford.net,(600)176-5674x84235,USA
2,CUST0003,Mr. Kevin Gamble,Female,33,Pune,2021-08-26,2026-04-18,24248,3.0,wrong_email.com,+1-322-053-8016x2164,India
3,CUST0004,Jennifer Santos,Female,60,Pune,2025-04-01,2025-12-18,26072,5.0,wrong_email.com,260.082.5758x91945,Canada
4,CUST0005,Andrea Jones,Female,45,Pune,2024-09-08,2025-10-02,24248,5.0,sancheztina@brooks.com,+1-609-632-0152,UK
...,...,...,...,...,...,...,...,...,...,...,...,...
995,CUST0996,Ryan Fox,Female,57,Pune,2024-09-10,2024-09-18,34413,1.0,marquezandrew@wang-king.com,942-513-9696,USA
996,CUST0997,Victoria Jones,Female,38,Pune,2025-02-07,2024-07-28,49247,5.0,welchanthony@gmail.com,914-950-1033x3539,USA
997,CUST0998,Dawn Adkins,Female,22,Indore,2024-04-12,2025-09-15,24248,5.0,marquezross@johnson.com,(145)156-7552,USA
998,CUST0999,Andrea Jones,Female,47,Mumbai,2021-11-18,2025-09-15,48567,3.0,twarren@vasquez.com,576-510-7252,India
999,CUST1000,Laura Moore,Female,39,Indore,2022-01-11,2025-04-25,24248,3.0,turnerchristopher@sanchez.info,(762)959-2129x0352,UK

In [413]:
 # dorp the phone number of the columns

In [414]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         1000 non-null   object
 1   Name                1000 non-null   object
 2   Gender              1000 non-null   object
 3   Age                 1000 non-null   int64
 4   City                1000 non-null   object
 5   Signup_Date         1000 non-null   object
 6   Last_Purchase_Date  1000 non-null   object
 7   Purchase_Amount     1000 non-null   int64
 8   Feedback_Score      1000 non-null   float64
 9   Email               1000 non-null   object
 10  Phone_Number        1000 non-null   object
 11  Country             1000 non-null   object
dtypes: float64(1), int64(2), object(9)
memory usage: 133.9+ KB

In [416]:
data["Country"].value_counts()

Country
Canada    409
USA       203
India     195
UK        193
Name: count, dtype: int64

In [417]:
data.to_csv("A3_(After_cleaning)dirty_customer_dataset_1000.csv")