In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data=pd.read_csv("A4_(before cleanng_data_set)Air Conditioners.csv")

In [4]:
data.head()

,name,main_category,sub_category,image,link,ratings,no_of_ratings,discount_price,actual_price
0,Lloyd 1.5 Ton 3 Star Inverter Split Ac (5 In 1...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/31UISB90sY...,https://www.amazon.in/Lloyd-Inverter-Convertib...,4.2,"2,255","₹32,999","₹58,990"
1,LG 1.5 Ton 5 Star AI DUAL Inverter Split AC (C...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/51JFb7FctD...,https://www.amazon.in/LG-Convertible-Anti-Viru...,4.2,"2,948","₹46,490","₹75,990"
2,LG 1 Ton 4 Star Ai Dual Inverter Split Ac (Cop...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/51JFb7FctD...,https://www.amazon.in/LG-Inverter-Convertible-...,4.2,"1,206","₹34,490","₹61,990"
3,LG 1.5 Ton 3 Star AI DUAL Inverter Split AC (C...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/51JFb7FctD...,https://www.amazon.in/LG-Convertible-Anti-Viru...,4.0,69,"₹37,990","₹68,990"
4,Carrier 1.5 Ton 3 Star Inverter Split AC (Copp...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/41lrtqXPiW...,https://www.amazon.in/Carrier-Inverter-Split-C...,4.1,630,"₹34,490","₹67,790"

In [5]:
data.tail()

,name,main_category,sub_category,image,link,ratings,no_of_ratings,discount_price,actual_price
715,Personal Air Conditioners Portable AC Mini Air...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/71RkCzQZyd...,https://www.amazon.in/Personal-Conditioners-Po...,NaN,NaN,"₹10,234","₹13,999"
716,Air Conditioner Fan Personal Desk Fan Space Ai...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/719ujjLfw7...,https://www.amazon.in/Conditioner-Personal-Eva...,NaN,NaN,NaN,"₹9,881"
717,"Portable Air Conditioners, Personal Air Condit...",appliances,Air Conditioners,https://m.media-amazon.com/images/I/71l59r1G-J...,https://www.amazon.in/Portable-Conditioners-Pe...,NaN,NaN,NaN,"₹6,361"
718,"Portable Air Conditioner Fan, Personal Air Coo...",appliances,Air Conditioners,https://m.media-amazon.com/images/I/61GXC1nOlS...,https://www.amazon.in/Portable-Conditioner-Per...,2.8,207,NaN,"₹7,671"
719,Air Choice Desktop Protable AC Cooler Fan For ...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/71yqMTaaWT...,https://www.amazon.in/Air-Choice-Desktop-Prota...,2.5,296,NaN,"₹8,592"

In [6]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 720 entries, 0 to 719
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   name            720 non-null    str
 1   main_category   720 non-null    str
 2   sub_category    720 non-null    str
 3   image           720 non-null    str
 4   link            720 non-null    str
 5   ratings         433 non-null    str
 6   no_of_ratings   433 non-null    str
 7   discount_price  457 non-null    str
 8   actual_price    500 non-null    str
dtypes: str(9)
memory usage: 50.8 KB

In [7]:
data.columns

Index(['name', 'main_category', 'sub_category', 'image', 'link', 'ratings',
       'no_of_ratings', 'discount_price', 'actual_price'],
      dtype='str')

In [8]:
# to convert in the data of column in the upper case 
new_columns=[]
for i in data.columns:
    new_columns.append(i.upper())
new_columns

['NAME',
 'MAIN_CATEGORY',
 'SUB_CATEGORY',
 'IMAGE',
 'LINK',
 'RATINGS',
 'NO_OF_RATINGS',
 'DISCOUNT_PRICE',
 'ACTUAL_PRICE']

In [9]:
data1=data.copy()

In [10]:
data1.columns=new_columns

In [12]:
data1.columns

Index(['NAME', 'MAIN_CATEGORY', 'SUB_CATEGORY', 'IMAGE', 'LINK', 'RATINGS',
       'NO_OF_RATINGS', 'DISCOUNT_PRICE', 'ACTUAL_PRICE'],
      dtype='str')

In [16]:
# know i am workin in the one by one columns
data1.info()

<class 'pandas.DataFrame'>
RangeIndex: 720 entries, 0 to 719
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   NAME            720 non-null    str
 1   MAIN_CATEGORY   720 non-null    str
 2   SUB_CATEGORY    720 non-null    str
 3   IMAGE           720 non-null    str
 4   LINK            720 non-null    str
 5   RATINGS         433 non-null    str
 6   NO_OF_RATINGS   433 non-null    str
 7   DISCOUNT_PRICE  457 non-null    str
 8   ACTUAL_PRICE    500 non-null    str
dtypes: str(9)
memory usage: 50.8 KB

In [15]:
data1.duplicated().sum() # the no present in the duplicate value in the columns

0

In [19]:
# so i am working in the the one by by one columns 
data1["NAME"].value_counts()

NAME
Samsung 1.5 Ton 3 Star Wind-Free Technology Inverter Split AC (Copper, Convertible 5-in-1 Cooling Mode, Anti-bacterial Fil...    3
White Westinghouse 1.5 ton 3 Star fix Speed Split AC                                                                             3
LG 1.5 Ton 5 Star AI DUAL Inverter Split AC (Copper, Super Convertible 6-in-1 Cooling, HD Filter with Anti-Virus Protectio...    2
Samsung 1.5 Ton 3 Star Wi-fi Enabled, Wind-Free Technology Inverter Split AC (Copper, Convertible 5-in-1 Cooling Mode, Ant...    2
LG 2.0 Ton 3 Star AI DUAL Inverter Split AC (Copper, Super Convertible 6-in-1 Cooling, 4 Way Swing, HD Filter with Anti-Vi...    2
                                                                                                                                ..
Efast Portable Air Conditioner, Cordless Personal Air Cooler Evaporative with 3 Speeds 7 Colors, Air Cooler for Room/Bedro...    1
Air Conditioner Fan Personal Desk Fan Space Air Cooler Portable Mini Cooling Fan Table Evaporative Air Humidifiers Ultra-Q...    1
Portable Air Conditioners, Personal Air Conditioner Fan with 3 Speeds 7 Colors, Cordless Evaporative Air Cooler with Handl...    1
Portable Air Conditioner Fan, Personal Air Cooler with Icebox, USB Desk Fan with 3 Speeds, Evaporative Air Cooler for Hom...     1
Air Choice Desktop Protable AC Cooler Fan For Indoor Use                                                                         1
Name: count, Length: 708, dtype: int64

In [32]:
j=0
for i in data1["NAME"]:
    if(i=="NaN"):
        j=j+1
print(j)
# ites note present in the null value of the columns

0

In [ ]:
# now i am working in the columns in the columns name data1["MAIN_CATEGORY"]

In [35]:
data1["MAIN_CATEGORY"].value_counts() # only data are present in the columns MAIN_CATEGORY

MAIN_CATEGORY
appliances    720
Name: count, dtype: int64

In [33]:
j=0
for i in data1["MAIN_CATEGORY"]:
    if(i=="NaN"):
        j=j+1
print(j)
# ites note present in the null value of the columns

0

In [ ]:
# now i am working in the columns in the columns name data1["SUB_CATEGORY"]

In [37]:
data1["SUB_CATEGORY"].value_counts()

SUB_CATEGORY
Air Conditioners    720
Name: count, dtype: int64

In [38]:
h=0
for i in data1["SUB_CATEGORY"]:
    if(i=="NaN"):
        h=h+1
print(h) # its not present in the null

0

In [ ]:
# now i am working in the columns in the columns name data1["IMAGEY"]

In [41]:
data1["IMAGE"].value_counts()

IMAGE
https://m.media-amazon.com/images/I/51JFb7FctDL._AC_UL320_.jpg                                      6
https://m.media-amazon.com/images/I/417b-AztnjL._AC_UL320_.jpg                                      5
https://m.media-amazon.com/images/I/51hbo8yQ1EL._AC_UL320_.jpg                                      5
https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/51v5Yi0ctkL._AC_UL320_.jpg    5
https://m.media-amazon.com/images/I/41e6oqY5-ZL._AC_UL320_.jpg                                      4
                                                                                                   ..
https://m.media-amazon.com/images/I/71RkCzQZydL._AC_UL320_.jpg                                      1
https://m.media-amazon.com/images/I/719ujjLfw7L._AC_UL320_.jpg                                      1
https://m.media-amazon.com/images/I/71l59r1G-JL._AC_UL320_.jpg                                      1
https://m.media-amazon.com/images/I/61GXC1nOlSL._AC_UL320_.jpg                                      1
https://m.media-amazon.com/images/I/71yqMTaaWTL._AC_UL320_.jpg                                      1
Name: count, Length: 635, dtype: int64

In [44]:
h=0
for i in data1["IMAGE"]:
    if(i=="NaN"):
        h=h+1
print(h)

0

In [45]:
data1["IMAGE"].isnull().sum()

0

In [46]:
# now i am working in the columns in the columns name data1[""]

In [47]:
data1["LINK"]

0      https://www.amazon.in/Lloyd-Inverter-Convertib...
1      https://www.amazon.in/LG-Convertible-Anti-Viru...
2      https://www.amazon.in/LG-Inverter-Convertible-...
3      https://www.amazon.in/LG-Convertible-Anti-Viru...
4      https://www.amazon.in/Carrier-Inverter-Split-C...
                             ...
715    https://www.amazon.in/Personal-Conditioners-Po...
716    https://www.amazon.in/Conditioner-Personal-Eva...
717    https://www.amazon.in/Portable-Conditioners-Pe...
718    https://www.amazon.in/Portable-Conditioner-Per...
719    https://www.amazon.in/Air-Choice-Desktop-Prota...
Name: LINK, Length: 720, dtype: str

In [ ]:
data1["LINK"].isnull().sum()

In [48]:
data1["LINK"].value_counts()

LINK
https://www.amazon.in/Lloyd-Inverter-Convertible-Anti-Viral-GLS18I3FWAMC/dp/B0BRKXTSBT/ref=sr_1_4?qid=1679134237&s=kitchen&sr=1-4              1
https://www.amazon.in/LG-Convertible-Anti-Virus-Protection-RS-Q19YNZE/dp/B0BQ3MXML8/ref=sr_1_5?qid=1679134237&s=kitchen&sr=1-5                 1
https://www.amazon.in/LG-Inverter-Convertible-protection-RS-Q13JNYE/dp/B0BPYN9JGF/ref=sr_1_6?qid=1679134237&s=kitchen&sr=1-6                   1
https://www.amazon.in/LG-Convertible-Anti-Virus-Protection-RS-Q19JNXE/dp/B0BQ3MJ1TG/ref=sr_1_7?qid=1679134237&s=kitchen&sr=1-7                 1
https://www.amazon.in/Carrier-Inverter-Split-Copper-Flexicool/dp/B0B67RLLJC/ref=sr_1_8?qid=1679134237&s=kitchen&sr=1-8                         1
                                                                                                                                              ..
https://www.amazon.in/Personal-Conditioners-Portable-Conditioner-Humidifier/dp/B09R1XY38M/ref=sr_1_722?qid=1679134274&s=kitchen&sr=1-722       1
https://www.amazon.in/Conditioner-Personal-Evaporative-Humidifiers-Ultra-Quiet/dp/B09QGD4MSX/ref=sr_1_723?qid=1679134274&s=kitchen&sr=1-723    1
https://www.amazon.in/Portable-Conditioners-Personal-Conditioner-Evaporative/dp/B09PTM62Z1/ref=sr_1_724?qid=1679134274&s=kitchen&sr=1-724      1
https://www.amazon.in/Portable-Conditioner-Personal-Evaporative-Humidifier/dp/B09MT926FQ/ref=sr_1_725?qid=1679134274&s=kitchen&sr=1-725        1
https://www.amazon.in/Air-Choice-Desktop-Protable-Cooler/dp/B09MS83NNG/ref=sr_1_726?qid=1679134274&s=kitchen&sr=1-726                          1
Name: count, Length: 720, dtype: int64

In [49]:
h=0
for i in data1["LINK"]:
    if(i=="NaN"):
        h=h+1
print(h)

0

In [50]:
data1.info()

<class 'pandas.DataFrame'>
RangeIndex: 720 entries, 0 to 719
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   NAME            720 non-null    str
 1   MAIN_CATEGORY   720 non-null    str
 2   SUB_CATEGORY    720 non-null    str
 3   IMAGE           720 non-null    str
 4   LINK            720 non-null    str
 5   RATINGS         433 non-null    str
 6   NO_OF_RATINGS   433 non-null    str
 7   DISCOUNT_PRICE  457 non-null    str
 8   ACTUAL_PRICE    500 non-null    str
dtypes: str(9)
memory usage: 50.8 KB

In [ ]:
# now i am working in the columns in the columns name data1["RATINGS"]

In [52]:
print(type(data1["RATINGS"][8]))

<class 'str'>

In [54]:
data1["RATINGS"].value_counts().mode()

0     1
1     2
2    10
Name: count, dtype: int64

In [55]:
data1["RATINGS"]=data1["RATINGS"].fillna(data1["RATINGS"].mode()[0])

In [57]:
data1["RATINGS"].isnull().sum()

0

In [58]:
data1["RATINGS"].value_counts()

RATINGS
4.0    343
4.1     41
5.0     41
4.2     38
3.9     29
4.3     19
3.5     18
3.6     18
3.7     16
3.0     16
3.4     15
3.8     13
3.2     13
3.3     12
1.0     12
4.6     10
4.4     10
Get     10
4.5      8
2.5      8
2.7      5
2.8      5
2.9      4
2.6      4
3.1      3
4.7      2
1.8      2
2.4      2
4.8      1
2.3      1
1.7      1
Name: count, dtype: int64

In [59]:
data1["RATINGS"]=data1["RATINGS"].str.replace("Get","4.4")

In [60]:
data1["RATINGS"].value_counts()

RATINGS
4.0    343
4.1     41
5.0     41
4.2     38
3.9     29
4.4     20
4.3     19
3.5     18
3.6     18
3.7     16
3.0     16
3.4     15
3.8     13
3.2     13
3.3     12
1.0     12
4.6     10
4.5      8
2.5      8
2.7      5
2.8      5
2.9      4
2.6      4
3.1      3
4.7      2
1.8      2
2.4      2
4.8      1
2.3      1
1.7      1
Name: count, dtype: int64

In [62]:
data1["RATINGS"].isnull().sum()

0

In [ ]:
# type conversion in the data columns  data1["RATINGS"]

In [64]:
data1["RATINGS"]=data1["RATINGS"].astype(float)

In [65]:
data1.info()

<class 'pandas.DataFrame'>
RangeIndex: 720 entries, 0 to 719
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   NAME            720 non-null    str
 1   MAIN_CATEGORY   720 non-null    str
 2   SUB_CATEGORY    720 non-null    str
 3   IMAGE           720 non-null    str
 4   LINK            720 non-null    str
 5   RATINGS         720 non-null    float64
 6   NO_OF_RATINGS   433 non-null    str
 7   DISCOUNT_PRICE  457 non-null    str
 8   ACTUAL_PRICE    500 non-null    str
dtypes: float64(1), str(8)
memory usage: 50.8 KB

In [68]:
data1.isnull().sum()

NAME                0
MAIN_CATEGORY       0
SUB_CATEGORY        0
IMAGE               0
LINK                0
RATINGS             0
NO_OF_RATINGS     287
DISCOUNT_PRICE    263
ACTUAL_PRICE      220
dtype: int64

In [71]:
data1["NO_OF_RATINGS"]

0      2,255
1      2,948
2      1,206
3         69
4        630
       ...
715      NaN
716      NaN
717      NaN
718      207
719      296
Name: NO_OF_RATINGS, Length: 720, dtype: str

In [75]:
data1["NO_OF_RATINGS"][0]

'2,255'

In [76]:
data1["NO_OF_RATINGS"]=data1["NO_OF_RATINGS"].str.replace(",","")

In [77]:
data1["NO_OF_RATINGS"]

0      2255
1      2948
2      1206
3        69
4       630
       ...
715     NaN
716     NaN
717     NaN
718     207
719     296
Name: NO_OF_RATINGS, Length: 720, dtype: str

In [84]:
data1["NO_OF_RATINGS"].value_counts().median()

1.0

In [85]:
data1["NO_OF_RATINGS"]=data1["NO_OF_RATINGS"].fillna("1")

In [95]:
data1["NO_OF_RATINGS"].value_counts().iloc[60:90]

NO_OF_RATINGS
1666    1
1097    1
1494    1
674     1
801     1
558     1
730     1
5073    1
568     1
3670    1
268     1
700     1
540     1
2178    1
1444    1
360     1
1208    1
341     1
925     1
3604    1
42      1
94      1
1866    1
292     1
1830    1
536     1
201     1
2722    1
202     1
1195    1
Name: count, dtype: int64

In [96]:
data1["NO_OF_RATINGS"]=data1["NO_OF_RATINGS"].str.replace(" ","")

In [99]:
data1["NO_OF_RATINGS"]=data1["NO_OF_RATINGS"].str.replace('Only2leftinstock.',"2")

In [104]:
data1["NO_OF_RATINGS"]

0      2255
1      2948
2      1206
3        69
4       630
       ...
715       1
716       1
717       1
718     207
719     296
Name: NO_OF_RATINGS, Length: 720, dtype: int64

In [ ]:
data1["NO_OF_RATINGS"]=data1["NO_OF_RATINGS"].astype(int)

In [103]:
import re

def clean_stock(x):
    num = re.findall(r'\d+', str(x))
    
    if len(num) > 0:
        return int(num[0])
    else:
        return 0

data1["NO_OF_RATINGS"] = data1["NO_OF_RATINGS"].apply(clean_stock)

In [105]:
data1["NO_OF_RATINGS"]=data1["NO_OF_RATINGS"].astype(int)

In [106]:
data1["NO_OF_RATINGS"]

0      2255
1      2948
2      1206
3        69
4       630
       ...
715       1
716       1
717       1
718     207
719     296
Name: NO_OF_RATINGS, Length: 720, dtype: int64

In [108]:
data1

,NAME,MAIN_CATEGORY,SUB_CATEGORY,IMAGE,LINK,RATINGS,NO_OF_RATINGS,DISCOUNT_PRICE,ACTUAL_PRICE
0,Lloyd 1.5 Ton 3 Star Inverter Split Ac (5 In 1...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/31UISB90sY...,https://www.amazon.in/Lloyd-Inverter-Convertib...,4.2,2255,"₹32,999","₹58,990"
1,LG 1.5 Ton 5 Star AI DUAL Inverter Split AC (C...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/51JFb7FctD...,https://www.amazon.in/LG-Convertible-Anti-Viru...,4.2,2948,"₹46,490","₹75,990"
2,LG 1 Ton 4 Star Ai Dual Inverter Split Ac (Cop...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/51JFb7FctD...,https://www.amazon.in/LG-Inverter-Convertible-...,4.2,1206,"₹34,490","₹61,990"
3,LG 1.5 Ton 3 Star AI DUAL Inverter Split AC (C...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/51JFb7FctD...,https://www.amazon.in/LG-Convertible-Anti-Viru...,4.0,69,"₹37,990","₹68,990"
4,Carrier 1.5 Ton 3 Star Inverter Split AC (Copp...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/41lrtqXPiW...,https://www.amazon.in/Carrier-Inverter-Split-C...,4.1,630,"₹34,490","₹67,790"
...,...,...,...,...,...,...,...,...,...
715,Personal Air Conditioners Portable AC Mini Air...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/71RkCzQZyd...,https://www.amazon.in/Personal-Conditioners-Po...,4.0,1,"₹10,234","₹13,999"
716,Air Conditioner Fan Personal Desk Fan Space Ai...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/719ujjLfw7...,https://www.amazon.in/Conditioner-Personal-Eva...,4.0,1,NaN,"₹9,881"
717,"Portable Air Conditioners, Personal Air Condit...",appliances,Air Conditioners,https://m.media-amazon.com/images/I/71l59r1G-J...,https://www.amazon.in/Portable-Conditioners-Pe...,4.0,1,NaN,"₹6,361"
718,"Portable Air Conditioner Fan, Personal Air Coo...",appliances,Air Conditioners,https://m.media-amazon.com/images/I/61GXC1nOlS...,https://www.amazon.in/Portable-Conditioner-Per...,2.8,207,NaN,"₹7,671"
719,Air Choice Desktop Protable AC Cooler Fan For ...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/71yqMTaaWT...,https://www.amazon.in/Air-Choice-Desktop-Prota...,2.5,296,NaN,"₹8,592"

In [109]:
data1["DISCOUNT_PRICE"]

0      ₹32,999
1      ₹46,490
2      ₹34,490
3      ₹37,990
4      ₹34,490
        ...
715    ₹10,234
716        NaN
717        NaN
718        NaN
719        NaN
Name: DISCOUNT_PRICE, Length: 720, dtype: str

In [110]:
data1["DISCOUNT_PRICE"][90]

'₹48,000'

In [111]:
data1["DISCOUNT_PRICE"]=data1["DISCOUNT_PRICE"].str.replace("₹","")

In [112]:
data1["DISCOUNT_PRICE"]=data1["DISCOUNT_PRICE"].str.replace(",","")

In [119]:
f=data1["DISCOUNT_PRICE"]

In [122]:
k=f.dropna()

In [129]:
k.astype(int).median()

39190.0

In [130]:
k.astype(int).mean()

40756.00656455142

In [131]:
k.astype(int).mode()

0    39990
Name: DISCOUNT_PRICE, dtype: int64

In [132]:
data1["DISCOUNT_PRICE"]=data1["DISCOUNT_PRICE"].fillna("40756")

In [133]:
data1["DISCOUNT_PRICE"]=data1["DISCOUNT_PRICE"].astype(int)

In [134]:
data1.info()

<class 'pandas.DataFrame'>
RangeIndex: 720 entries, 0 to 719
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   NAME            720 non-null    str
 1   MAIN_CATEGORY   720 non-null    str
 2   SUB_CATEGORY    720 non-null    str
 3   IMAGE           720 non-null    str
 4   LINK            720 non-null    str
 5   RATINGS         720 non-null    float64
 6   NO_OF_RATINGS   720 non-null    int64
 7   DISCOUNT_PRICE  720 non-null    int64
 8   ACTUAL_PRICE    500 non-null    str
dtypes: float64(1), int64(2), str(6)
memory usage: 50.8 KB

In [135]:
# koow i am working in the columns in the data1["ACTUAL_PRICE"]

In [136]:
data1["ACTUAL_PRICE"]

0      ₹58,990
1      ₹75,990
2      ₹61,990
3      ₹68,990
4      ₹67,790
        ...
715    ₹13,999
716     ₹9,881
717     ₹6,361
718     ₹7,671
719     ₹8,592
Name: ACTUAL_PRICE, Length: 720, dtype: str

In [137]:
data1["ACTUAL_PRICE"][90]

'₹71,750'

In [138]:
data1["ACTUAL_PRICE"]=data1["ACTUAL_PRICE"].str.replace('₹',"")

In [139]:
data1["ACTUAL_PRICE"]=data1["ACTUAL_PRICE"].str.replace(',',"")

In [140]:
data1["ACTUAL_PRICE"]

0      58990
1      75990
2      61990
3      68990
4      67790
       ...
715    13999
716     9881
717     6361
718     7671
719     8592
Name: ACTUAL_PRICE, Length: 720, dtype: str

In [141]:
data1["ACTUAL_PRICE"].value_counts()

ACTUAL_PRICE
59990    15
55990    11
75990     9
58990     7
61990     7
         ..
13999     1
9881      1
6361      1
7671      1
8592      1
Name: count, Length: 296, dtype: int64

In [144]:
data1["ACTUAL_PRICE"].value_counts().mode().values

array([1])

In [146]:
c=data1["ACTUAL_PRICE"]

In [147]:
k=c.dropna()

In [151]:
k.astype(float).mean()

54815.22724

In [152]:
k.astype(float).median()

56990.0

In [153]:
data1["ACTUAL_PRICE"]=data1["ACTUAL_PRICE"].fillna("56990.0")

In [156]:
data1["ACTUAL_PRICE"]=data1["ACTUAL_PRICE"].astype(float)

In [157]:
data1["ACTUAL_PRICE"]=data1["ACTUAL_PRICE"].astype(int)

In [158]:
data1

,NAME,MAIN_CATEGORY,SUB_CATEGORY,IMAGE,LINK,RATINGS,NO_OF_RATINGS,DISCOUNT_PRICE,ACTUAL_PRICE
0,Lloyd 1.5 Ton 3 Star Inverter Split Ac (5 In 1...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/31UISB90sY...,https://www.amazon.in/Lloyd-Inverter-Convertib...,4.2,2255,32999,58990
1,LG 1.5 Ton 5 Star AI DUAL Inverter Split AC (C...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/51JFb7FctD...,https://www.amazon.in/LG-Convertible-Anti-Viru...,4.2,2948,46490,75990
2,LG 1 Ton 4 Star Ai Dual Inverter Split Ac (Cop...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/51JFb7FctD...,https://www.amazon.in/LG-Inverter-Convertible-...,4.2,1206,34490,61990
3,LG 1.5 Ton 3 Star AI DUAL Inverter Split AC (C...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/51JFb7FctD...,https://www.amazon.in/LG-Convertible-Anti-Viru...,4.0,69,37990,68990
4,Carrier 1.5 Ton 3 Star Inverter Split AC (Copp...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/41lrtqXPiW...,https://www.amazon.in/Carrier-Inverter-Split-C...,4.1,630,34490,67790
...,...,...,...,...,...,...,...,...,...
715,Personal Air Conditioners Portable AC Mini Air...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/71RkCzQZyd...,https://www.amazon.in/Personal-Conditioners-Po...,4.0,1,10234,13999
716,Air Conditioner Fan Personal Desk Fan Space Ai...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/719ujjLfw7...,https://www.amazon.in/Conditioner-Personal-Eva...,4.0,1,40756,9881
717,"Portable Air Conditioners, Personal Air Condit...",appliances,Air Conditioners,https://m.media-amazon.com/images/I/71l59r1G-J...,https://www.amazon.in/Portable-Conditioners-Pe...,4.0,1,40756,6361
718,"Portable Air Conditioner Fan, Personal Air Coo...",appliances,Air Conditioners,https://m.media-amazon.com/images/I/61GXC1nOlS...,https://www.amazon.in/Portable-Conditioner-Per...,2.8,207,40756,7671
719,Air Choice Desktop Protable AC Cooler Fan For ...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/71yqMTaaWT...,https://www.amazon.in/Air-Choice-Desktop-Prota...,2.5,296,40756,8592

In [159]:
data1.to_csv("A4_(after cleanng_data_set)Air Conditioners.csv",index=False)