In [133]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
data=pd.read_csv("beafore_cleaning_amazon_product.csv")

In [134]:
data

,Unnamed: 0,asin,product_title,product_price,product_original_price,currency,product_star_rating,product_num_ratings,product_url,product_photo,...,is_best_seller,is_amazon_choice,is_prime,climate_pledge_friendly,sales_volume,delivery,has_variations,product_availability,unit_price,unit_count
0,0,B0BQ118F2T,Moto G Play 2023 3-Day Battery Unlocked Made f...,$99.99,$169.99,USD,4.0,2929,https://www.amazon.com/dp/B0BQ118F2T,https://m.media-amazon.com/images/I/61K1Fz5Lxv...,...,False,False,True,False,6K+ bought in past month,"FREE delivery Tue, Aug 6",True,NaN,NaN,NaN
1,1,B0CTD47P22,"SAMSUNG Galaxy A15 5G (SM-156M/DSN), 128GB 6GB...",$149.74,$158.00,USD,4.2,135,https://www.amazon.com/dp/B0CTD47P22,https://m.media-amazon.com/images/I/51QhB2CfqS...,...,False,False,True,False,3K+ bought in past month,"FREE delivery Wed, Aug 7 Only 7 left in stock ...",False,Only 7 left in stock - order soon.,NaN,NaN
2,2,B0CHH6X6H2,Total by Verizon | Samsung Galaxy A03s | Locke...,$49.88,NaN,USD,3.9,205,https://www.amazon.com/dp/B0CHH6X6H2,https://m.media-amazon.com/images/I/812woqv69C...,...,False,False,True,False,2K+ bought in past month,"FREE delivery Tue, Aug 6",False,NaN,NaN,NaN
3,3,B0BZ9XNBRB,Google Pixel 7a - Unlocked Android Cell Phone ...,$335.00,$499.00,USD,4.3,2248,https://www.amazon.com/dp/B0BZ9XNBRB,https://m.media-amazon.com/images/I/61r7cCpQPl...,...,False,False,False,False,10K+ bought in past month,FREE delivery Aug 6 - 8,True,NaN,NaN,NaN
4,4,B0CN1QSH8Q,"SAMSUNG Galaxy A15 5G A Series Cell Phone, 128...",$199.99,NaN,USD,4.1,423,https://www.amazon.com/dp/B0CN1QSH8Q,https://m.media-amazon.com/images/I/61s0ZzwzSC...,...,False,False,True,True,3K+ bought in past month,"FREE delivery Tue, Aug 6",True,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,59,B0D6LWXK1R,Greatish Hits: I Followed My Dreams and My Dre...,$34.98,NaN,USD,NaN,0,https://www.amazon.com/dp/B0D6LWXK1R,https://m.media-amazon.com/images/I/815otxMW0i...,...,False,False,False,False,50+ bought in past month,FREE delivery on $35 shipped by Amazon.This ti...,False,NaN,NaN,NaN
60,60,B0CLKQF5HR,Swan Song,$14.99,$30.00,USD,4.4,14471,https://www.amazon.com/dp/B0CLKQF5HR,https://m.media-amazon.com/images/I/71dSn3QCY6...,...,True,False,False,False,Print List Price:,Available instantly,False,NaN,NaN,NaN
61,61,B0BZFHK12K,Bluey: Let&#x27;s Play!,$0.00,NaN,USD,3.5,270,https://www.amazon.com/dp/B0BZFHK12K,https://m.media-amazon.com/images/I/617GUqQEIC...,...,False,False,False,False,"Jul 7, 2023",Available instantly on compatible devices,False,NaN,NaN,NaN
62,62,B09Z7J4L6X,Xbox Wireless Controller – Sky Cipher Special ...,$69.99,NaN,USD,2.6,12,https://www.amazon.com/dp/B09Z7J4L6X,https://m.media-amazon.com/images/I/71i2tEKlZ2...,...,True,False,False,False,"Aug 13, 2024",FREE deliveryThis item will be released on Aug...,False,NaN,NaN,NaN
63,63,B0CT2R7199,HP DeskJet 2855e Wireless All-in-One Color Ink...,$59.99,$84.99,USD,4.0,48154,https://www.amazon.com/dp/B0CT2R7199,https://m.media-amazon.com/images/I/61+biEwB1h...,...,True,False,False,True,80K+ bought in past month,FREE delivery,False,NaN,NaN,NaN

In [135]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64 entries, 0 to 63
Data columns (total 22 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Unnamed: 0                   64 non-null     int64
 1   asin                         64 non-null     object
 2   product_title                64 non-null     object
 3   product_price                64 non-null     object
 4   product_original_price       27 non-null     object
 5   currency                     64 non-null     object
 6   product_star_rating          54 non-null     float64
 7   product_num_ratings          64 non-null     int64
 8   product_url                  64 non-null     object
 9   product_photo                64 non-null     object
 10  product_num_offers           64 non-null     int64
 11  product_minimum_offer_price  64 non-null     object
 12  is_best_seller               64 non-null     bool
 13  is_amazon_choice             64 non-null     bool
 14  is_prime                     64 non-null     bool
 15  climate_pledge_friendly      64 non-null     bool
 16  sales_volume                 61 non-null     object
 17  delivery                     63 non-null     object
 18  has_variations               64 non-null     bool
 19  product_availability         1 non-null      object
 20  unit_price                   5 non-null      object
 21  unit_count                   5 non-null      float64
dtypes: bool(5), float64(2), int64(3), object(12)
memory usage: 8.9+ KB

In [136]:
data.isnull().sum()

Unnamed: 0                      0
asin                            0
product_title                   0
product_price                   0
product_original_price         37
currency                        0
product_star_rating            10
product_num_ratings             0
product_url                     0
product_photo                   0
product_num_offers              0
product_minimum_offer_price     0
is_best_seller                  0
is_amazon_choice                0
is_prime                        0
climate_pledge_friendly         0
sales_volume                    3
delivery                        1
has_variations                  0
product_availability           63
unit_price                     59
unit_count                     59
dtype: int64

In [137]:
data.shape

(64, 22)

In [138]:
data.columns

Index(['Unnamed: 0', 'asin', 'product_title', 'product_price',
       'product_original_price', 'currency', 'product_star_rating',
       'product_num_ratings', 'product_url', 'product_photo',
       'product_num_offers', 'product_minimum_offer_price', 'is_best_seller',
       'is_amazon_choice', 'is_prime', 'climate_pledge_friendly',
       'sales_volume', 'delivery', 'has_variations', 'product_availability',
       'unit_price', 'unit_count'],
      dtype='object')

In [139]:
 # the first of the columns convert in the ane form like(upper case)
#'Unnamed: 0'first of the drop down the 
data=data.drop(columns=["Unnamed: 0"])

In [140]:
data.head(6)

,asin,product_title,product_price,product_original_price,currency,product_star_rating,product_num_ratings,product_url,product_photo,product_num_offers,...,is_best_seller,is_amazon_choice,is_prime,climate_pledge_friendly,sales_volume,delivery,has_variations,product_availability,unit_price,unit_count
0,B0BQ118F2T,Moto G Play 2023 3-Day Battery Unlocked Made f...,$99.99,$169.99,USD,4.0,2929,https://www.amazon.com/dp/B0BQ118F2T,https://m.media-amazon.com/images/I/61K1Fz5Lxv...,10,...,False,False,True,False,6K+ bought in past month,"FREE delivery Tue, Aug 6",True,NaN,NaN,NaN
1,B0CTD47P22,"SAMSUNG Galaxy A15 5G (SM-156M/DSN), 128GB 6GB...",$149.74,$158.00,USD,4.2,135,https://www.amazon.com/dp/B0CTD47P22,https://m.media-amazon.com/images/I/51QhB2CfqS...,8,...,False,False,True,False,3K+ bought in past month,"FREE delivery Wed, Aug 7 Only 7 left in stock ...",False,Only 7 left in stock - order soon.,NaN,NaN
2,B0CHH6X6H2,Total by Verizon | Samsung Galaxy A03s | Locke...,$49.88,NaN,USD,3.9,205,https://www.amazon.com/dp/B0CHH6X6H2,https://m.media-amazon.com/images/I/812woqv69C...,1,...,False,False,True,False,2K+ bought in past month,"FREE delivery Tue, Aug 6",False,NaN,NaN,NaN
3,B0BZ9XNBRB,Google Pixel 7a - Unlocked Android Cell Phone ...,$335.00,$499.00,USD,4.3,2248,https://www.amazon.com/dp/B0BZ9XNBRB,https://m.media-amazon.com/images/I/61r7cCpQPl...,30,...,False,False,False,False,10K+ bought in past month,FREE delivery Aug 6 - 8,True,NaN,NaN,NaN
4,B0CN1QSH8Q,"SAMSUNG Galaxy A15 5G A Series Cell Phone, 128...",$199.99,NaN,USD,4.1,423,https://www.amazon.com/dp/B0CN1QSH8Q,https://m.media-amazon.com/images/I/61s0ZzwzSC...,2,...,False,False,True,True,3K+ bought in past month,"FREE delivery Tue, Aug 6",True,NaN,NaN,NaN
5,B0CSB22F9C,"Samsung Galaxy A15 (SM-155M/DSN), 128GB 6GB RA...",$129.99,$137.65,USD,4.2,578,https://www.amazon.com/dp/B0CSB22F9C,https://m.media-amazon.com/images/I/51rp0nqaPo...,13,...,False,False,True,False,3K+ bought in past month,"FREE delivery Tue, Aug 6",False,NaN,NaN,NaN

In [141]:
data.tail(6)

,asin,product_title,product_price,product_original_price,currency,product_star_rating,product_num_ratings,product_url,product_photo,product_num_offers,...,is_best_seller,is_amazon_choice,is_prime,climate_pledge_friendly,sales_volume,delivery,has_variations,product_availability,unit_price,unit_count
58,B0117U0G3M,TikTok,$0.00,NaN,USD,4.2,140637,https://www.amazon.com/dp/B0117U0G3M,https://m.media-amazon.com/images/I/41b3zsiq4p...,1,...,False,False,False,False,"Jul 8, 2015",Available instantly on compatible devices,False,NaN,NaN,NaN
59,B0D6LWXK1R,Greatish Hits: I Followed My Dreams and My Dre...,$34.98,NaN,USD,NaN,0,https://www.amazon.com/dp/B0D6LWXK1R,https://m.media-amazon.com/images/I/815otxMW0i...,1,...,False,False,False,False,50+ bought in past month,FREE delivery on $35 shipped by Amazon.This ti...,False,NaN,NaN,NaN
60,B0CLKQF5HR,Swan Song,$14.99,$30.00,USD,4.4,14471,https://www.amazon.com/dp/B0CLKQF5HR,https://m.media-amazon.com/images/I/71dSn3QCY6...,1,...,True,False,False,False,Print List Price:,Available instantly,False,NaN,NaN,NaN
61,B0BZFHK12K,Bluey: Let&#x27;s Play!,$0.00,NaN,USD,3.5,270,https://www.amazon.com/dp/B0BZFHK12K,https://m.media-amazon.com/images/I/617GUqQEIC...,1,...,False,False,False,False,"Jul 7, 2023",Available instantly on compatible devices,False,NaN,NaN,NaN
62,B09Z7J4L6X,Xbox Wireless Controller – Sky Cipher Special ...,$69.99,NaN,USD,2.6,12,https://www.amazon.com/dp/B09Z7J4L6X,https://m.media-amazon.com/images/I/71i2tEKlZ2...,1,...,True,False,False,False,"Aug 13, 2024",FREE deliveryThis item will be released on Aug...,False,NaN,NaN,NaN
63,B0CT2R7199,HP DeskJet 2855e Wireless All-in-One Color Ink...,$59.99,$84.99,USD,4.0,48154,https://www.amazon.com/dp/B0CT2R7199,https://m.media-amazon.com/images/I/61+biEwB1h...,1,...,True,False,False,True,80K+ bought in past month,FREE delivery,False,NaN,NaN,NaN

In [142]:
# the columns name convert into the single form

In [143]:
new_column=[]
for i in data.columns:
    new_column.append(i.upper())

In [144]:
new_column

['ASIN',
 'PRODUCT_TITLE',
 'PRODUCT_PRICE',
 'PRODUCT_ORIGINAL_PRICE',
 'CURRENCY',
 'PRODUCT_STAR_RATING',
 'PRODUCT_NUM_RATINGS',
 'PRODUCT_URL',
 'PRODUCT_PHOTO',
 'PRODUCT_NUM_OFFERS',
 'PRODUCT_MINIMUM_OFFER_PRICE',
 'IS_BEST_SELLER',
 'IS_AMAZON_CHOICE',
 'IS_PRIME',
 'CLIMATE_PLEDGE_FRIENDLY',
 'SALES_VOLUME',
 'DELIVERY',
 'HAS_VARIATIONS',
 'PRODUCT_AVAILABILITY',
 'UNIT_PRICE',
 'UNIT_COUNT']

In [145]:
# to the copy
data1=data.copy()

In [146]:
data1.columns=new_column

In [147]:
data1

,ASIN,PRODUCT_TITLE,PRODUCT_PRICE,PRODUCT_ORIGINAL_PRICE,CURRENCY,PRODUCT_STAR_RATING,PRODUCT_NUM_RATINGS,PRODUCT_URL,PRODUCT_PHOTO,PRODUCT_NUM_OFFERS,...,IS_BEST_SELLER,IS_AMAZON_CHOICE,IS_PRIME,CLIMATE_PLEDGE_FRIENDLY,SALES_VOLUME,DELIVERY,HAS_VARIATIONS,PRODUCT_AVAILABILITY,UNIT_PRICE,UNIT_COUNT
0,B0BQ118F2T,Moto G Play 2023 3-Day Battery Unlocked Made f...,$99.99,$169.99,USD,4.0,2929,https://www.amazon.com/dp/B0BQ118F2T,https://m.media-amazon.com/images/I/61K1Fz5Lxv...,10,...,False,False,True,False,6K+ bought in past month,"FREE delivery Tue, Aug 6",True,NaN,NaN,NaN
1,B0CTD47P22,"SAMSUNG Galaxy A15 5G (SM-156M/DSN), 128GB 6GB...",$149.74,$158.00,USD,4.2,135,https://www.amazon.com/dp/B0CTD47P22,https://m.media-amazon.com/images/I/51QhB2CfqS...,8,...,False,False,True,False,3K+ bought in past month,"FREE delivery Wed, Aug 7 Only 7 left in stock ...",False,Only 7 left in stock - order soon.,NaN,NaN
2,B0CHH6X6H2,Total by Verizon | Samsung Galaxy A03s | Locke...,$49.88,NaN,USD,3.9,205,https://www.amazon.com/dp/B0CHH6X6H2,https://m.media-amazon.com/images/I/812woqv69C...,1,...,False,False,True,False,2K+ bought in past month,"FREE delivery Tue, Aug 6",False,NaN,NaN,NaN
3,B0BZ9XNBRB,Google Pixel 7a - Unlocked Android Cell Phone ...,$335.00,$499.00,USD,4.3,2248,https://www.amazon.com/dp/B0BZ9XNBRB,https://m.media-amazon.com/images/I/61r7cCpQPl...,30,...,False,False,False,False,10K+ bought in past month,FREE delivery Aug 6 - 8,True,NaN,NaN,NaN
4,B0CN1QSH8Q,"SAMSUNG Galaxy A15 5G A Series Cell Phone, 128...",$199.99,NaN,USD,4.1,423,https://www.amazon.com/dp/B0CN1QSH8Q,https://m.media-amazon.com/images/I/61s0ZzwzSC...,2,...,False,False,True,True,3K+ bought in past month,"FREE delivery Tue, Aug 6",True,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,B0D6LWXK1R,Greatish Hits: I Followed My Dreams and My Dre...,$34.98,NaN,USD,NaN,0,https://www.amazon.com/dp/B0D6LWXK1R,https://m.media-amazon.com/images/I/815otxMW0i...,1,...,False,False,False,False,50+ bought in past month,FREE delivery on $35 shipped by Amazon.This ti...,False,NaN,NaN,NaN
60,B0CLKQF5HR,Swan Song,$14.99,$30.00,USD,4.4,14471,https://www.amazon.com/dp/B0CLKQF5HR,https://m.media-amazon.com/images/I/71dSn3QCY6...,1,...,True,False,False,False,Print List Price:,Available instantly,False,NaN,NaN,NaN
61,B0BZFHK12K,Bluey: Let&#x27;s Play!,$0.00,NaN,USD,3.5,270,https://www.amazon.com/dp/B0BZFHK12K,https://m.media-amazon.com/images/I/617GUqQEIC...,1,...,False,False,False,False,"Jul 7, 2023",Available instantly on compatible devices,False,NaN,NaN,NaN
62,B09Z7J4L6X,Xbox Wireless Controller – Sky Cipher Special ...,$69.99,NaN,USD,2.6,12,https://www.amazon.com/dp/B09Z7J4L6X,https://m.media-amazon.com/images/I/71i2tEKlZ2...,1,...,True,False,False,False,"Aug 13, 2024",FREE deliveryThis item will be released on Aug...,False,NaN,NaN,NaN
63,B0CT2R7199,HP DeskJet 2855e Wireless All-in-One Color Ink...,$59.99,$84.99,USD,4.0,48154,https://www.amazon.com/dp/B0CT2R7199,https://m.media-amazon.com/images/I/61+biEwB1h...,1,...,True,False,False,True,80K+ bought in past month,FREE delivery,False,NaN,NaN,NaN

In [148]:
data1.columns

Index(['ASIN', 'PRODUCT_TITLE', 'PRODUCT_PRICE', 'PRODUCT_ORIGINAL_PRICE',
       'CURRENCY', 'PRODUCT_STAR_RATING', 'PRODUCT_NUM_RATINGS', 'PRODUCT_URL',
       'PRODUCT_PHOTO', 'PRODUCT_NUM_OFFERS', 'PRODUCT_MINIMUM_OFFER_PRICE',
       'IS_BEST_SELLER', 'IS_AMAZON_CHOICE', 'IS_PRIME',
       'CLIMATE_PLEDGE_FRIENDLY', 'SALES_VOLUME', 'DELIVERY', 'HAS_VARIATIONS',
       'PRODUCT_AVAILABILITY', 'UNIT_PRICE', 'UNIT_COUNT'],
      dtype='object')

In [149]:
# to drop the dubblicate value the present in the dataset
data1.drop_duplicates().value_counts().sum()  # the duplicate value not present in the the data set

np.int64(0)

In [150]:
data1.drop_duplicates()

,ASIN,PRODUCT_TITLE,PRODUCT_PRICE,PRODUCT_ORIGINAL_PRICE,CURRENCY,PRODUCT_STAR_RATING,PRODUCT_NUM_RATINGS,PRODUCT_URL,PRODUCT_PHOTO,PRODUCT_NUM_OFFERS,...,IS_BEST_SELLER,IS_AMAZON_CHOICE,IS_PRIME,CLIMATE_PLEDGE_FRIENDLY,SALES_VOLUME,DELIVERY,HAS_VARIATIONS,PRODUCT_AVAILABILITY,UNIT_PRICE,UNIT_COUNT
0,B0BQ118F2T,Moto G Play 2023 3-Day Battery Unlocked Made f...,$99.99,$169.99,USD,4.0,2929,https://www.amazon.com/dp/B0BQ118F2T,https://m.media-amazon.com/images/I/61K1Fz5Lxv...,10,...,False,False,True,False,6K+ bought in past month,"FREE delivery Tue, Aug 6",True,NaN,NaN,NaN
1,B0CTD47P22,"SAMSUNG Galaxy A15 5G (SM-156M/DSN), 128GB 6GB...",$149.74,$158.00,USD,4.2,135,https://www.amazon.com/dp/B0CTD47P22,https://m.media-amazon.com/images/I/51QhB2CfqS...,8,...,False,False,True,False,3K+ bought in past month,"FREE delivery Wed, Aug 7 Only 7 left in stock ...",False,Only 7 left in stock - order soon.,NaN,NaN
2,B0CHH6X6H2,Total by Verizon | Samsung Galaxy A03s | Locke...,$49.88,NaN,USD,3.9,205,https://www.amazon.com/dp/B0CHH6X6H2,https://m.media-amazon.com/images/I/812woqv69C...,1,...,False,False,True,False,2K+ bought in past month,"FREE delivery Tue, Aug 6",False,NaN,NaN,NaN
3,B0BZ9XNBRB,Google Pixel 7a - Unlocked Android Cell Phone ...,$335.00,$499.00,USD,4.3,2248,https://www.amazon.com/dp/B0BZ9XNBRB,https://m.media-amazon.com/images/I/61r7cCpQPl...,30,...,False,False,False,False,10K+ bought in past month,FREE delivery Aug 6 - 8,True,NaN,NaN,NaN
4,B0CN1QSH8Q,"SAMSUNG Galaxy A15 5G A Series Cell Phone, 128...",$199.99,NaN,USD,4.1,423,https://www.amazon.com/dp/B0CN1QSH8Q,https://m.media-amazon.com/images/I/61s0ZzwzSC...,2,...,False,False,True,True,3K+ bought in past month,"FREE delivery Tue, Aug 6",True,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,B0D6LWXK1R,Greatish Hits: I Followed My Dreams and My Dre...,$34.98,NaN,USD,NaN,0,https://www.amazon.com/dp/B0D6LWXK1R,https://m.media-amazon.com/images/I/815otxMW0i...,1,...,False,False,False,False,50+ bought in past month,FREE delivery on $35 shipped by Amazon.This ti...,False,NaN,NaN,NaN
60,B0CLKQF5HR,Swan Song,$14.99,$30.00,USD,4.4,14471,https://www.amazon.com/dp/B0CLKQF5HR,https://m.media-amazon.com/images/I/71dSn3QCY6...,1,...,True,False,False,False,Print List Price:,Available instantly,False,NaN,NaN,NaN
61,B0BZFHK12K,Bluey: Let&#x27;s Play!,$0.00,NaN,USD,3.5,270,https://www.amazon.com/dp/B0BZFHK12K,https://m.media-amazon.com/images/I/617GUqQEIC...,1,...,False,False,False,False,"Jul 7, 2023",Available instantly on compatible devices,False,NaN,NaN,NaN
62,B09Z7J4L6X,Xbox Wireless Controller – Sky Cipher Special ...,$69.99,NaN,USD,2.6,12,https://www.amazon.com/dp/B09Z7J4L6X,https://m.media-amazon.com/images/I/71i2tEKlZ2...,1,...,True,False,False,False,"Aug 13, 2024",FREE deliveryThis item will be released on Aug...,False,NaN,NaN,NaN
63,B0CT2R7199,HP DeskJet 2855e Wireless All-in-One Color Ink...,$59.99,$84.99,USD,4.0,48154,https://www.amazon.com/dp/B0CT2R7199,https://m.media-amazon.com/images/I/61+biEwB1h...,1,...,True,False,False,True,80K+ bought in past month,FREE delivery,False,NaN,NaN,NaN

In [151]:
data1.columns

Index(['ASIN', 'PRODUCT_TITLE', 'PRODUCT_PRICE', 'PRODUCT_ORIGINAL_PRICE',
       'CURRENCY', 'PRODUCT_STAR_RATING', 'PRODUCT_NUM_RATINGS', 'PRODUCT_URL',
       'PRODUCT_PHOTO', 'PRODUCT_NUM_OFFERS', 'PRODUCT_MINIMUM_OFFER_PRICE',
       'IS_BEST_SELLER', 'IS_AMAZON_CHOICE', 'IS_PRIME',
       'CLIMATE_PLEDGE_FRIENDLY', 'SALES_VOLUME', 'DELIVERY', 'HAS_VARIATIONS',
       'PRODUCT_AVAILABILITY', 'UNIT_PRICE', 'UNIT_COUNT'],
      dtype='object')

In [152]:
#  TO take the usable columns in the dataset
#so ot take the

In [153]:
take_columns=['ASIN', 'PRODUCT_TITLE', 'PRODUCT_PRICE', 'PRODUCT_ORIGINAL_PRICE',
       'CURRENCY', 'PRODUCT_STAR_RATING','DELIVERY']

In [154]:
take_columns

['ASIN',
 'PRODUCT_TITLE',
 'PRODUCT_PRICE',
 'PRODUCT_ORIGINAL_PRICE',
 'CURRENCY',
 'PRODUCT_STAR_RATING',
 'DELIVERY']

In [155]:
to_drop_columns=['PRODUCT_URL',
       'PRODUCT_PHOTO', 'PRODUCT_NUM_OFFERS', 'PRODUCT_MINIMUM_OFFER_PRICE',
       'IS_BEST_SELLER', 'IS_AMAZON_CHOICE', 'IS_PRIME',
       'CLIMATE_PLEDGE_FRIENDLY', 'SALES_VOLUME','HAS_VARIATIONS',
       'PRODUCT_AVAILABILITY', 'UNIT_PRICE', 'UNIT_COUNT']

In [156]:
data1=data1.drop(columns=to_drop_columns)

In [157]:
data1.columns

Index(['ASIN', 'PRODUCT_TITLE', 'PRODUCT_PRICE', 'PRODUCT_ORIGINAL_PRICE',
       'CURRENCY', 'PRODUCT_STAR_RATING', 'PRODUCT_NUM_RATINGS', 'DELIVERY'],
      dtype='object')

In [158]:
# now i am working in the columns one by one
# the we cheak the duplicate vlaue
data1.duplicated().sum() # its not present in the duplicate the value of the dataset

np.int64(0)

In [159]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64 entries, 0 to 63
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ASIN                    64 non-null     object
 1   PRODUCT_TITLE           64 non-null     object
 2   PRODUCT_PRICE           64 non-null     object
 3   PRODUCT_ORIGINAL_PRICE  27 non-null     object
 4   CURRENCY                64 non-null     object
 5   PRODUCT_STAR_RATING     54 non-null     float64
 6   PRODUCT_NUM_RATINGS     64 non-null     int64
 7   DELIVERY                63 non-null     object
dtypes: float64(1), int64(1), object(6)
memory usage: 4.1+ KB

In [160]:
data1.head(3)

,ASIN,PRODUCT_TITLE,PRODUCT_PRICE,PRODUCT_ORIGINAL_PRICE,CURRENCY,PRODUCT_STAR_RATING,PRODUCT_NUM_RATINGS,DELIVERY
0,B0BQ118F2T,Moto G Play 2023 3-Day Battery Unlocked Made f...,$99.99,$169.99,USD,4.0,2929,"FREE delivery Tue, Aug 6"
1,B0CTD47P22,"SAMSUNG Galaxy A15 5G (SM-156M/DSN), 128GB 6GB...",$149.74,$158.00,USD,4.2,135,"FREE delivery Wed, Aug 7 Only 7 left in stock ..."
2,B0CHH6X6H2,Total by Verizon | Samsung Galaxy A03s | Locke...,$49.88,NaN,USD,3.9,205,"FREE delivery Tue, Aug 6"

In [161]:
data1.isnull().sum()

ASIN                       0
PRODUCT_TITLE              0
PRODUCT_PRICE              0
PRODUCT_ORIGINAL_PRICE    37
CURRENCY                   0
PRODUCT_STAR_RATING       10
PRODUCT_NUM_RATINGS        0
DELIVERY                   1
dtype: int64

In [162]:
# to working in the the columns data1["PRODUCT_PRICE"]

In [163]:
type(data1["PRODUCT_PRICE"][9]) # 
data1["PRODUCT_PRICE"][45] #first all remove the dollar sing of the each row

'$0.00'

In [164]:
data1["PRODUCT_PRICE"]=data1["PRODUCT_PRICE"].str.replace("$","") # then convert into the  data type

In [165]:
data1["PRODUCT_PRICE"][45]

'0.00'

In [166]:
data1["PRODUCT_PRICE"]=data1["PRODUCT_PRICE"].astype(float)

In [167]:
type(data1["PRODUCT_PRICE"][8])

numpy.float64

In [168]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64 entries, 0 to 63
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ASIN                    64 non-null     object
 1   PRODUCT_TITLE           64 non-null     object
 2   PRODUCT_PRICE           64 non-null     float64
 3   PRODUCT_ORIGINAL_PRICE  27 non-null     object
 4   CURRENCY                64 non-null     object
 5   PRODUCT_STAR_RATING     54 non-null     float64
 6   PRODUCT_NUM_RATINGS     64 non-null     int64
 7   DELIVERY                63 non-null     object
dtypes: float64(2), int64(1), object(5)
memory usage: 4.1+ KB

In [169]:
# now i am working in the columns  PRODUCT_ORIGINAL_PRICE

In [170]:
data1["PRODUCT_ORIGINAL_PRICE"].isnull().sum()

np.int64(37)

In [171]:
type(data1["PRODUCT_ORIGINAL_PRICE"][9])
data1["PRODUCT_ORIGINAL_PRICE"][9]

'$149.99'

In [172]:
# to remove the $ sing in the each row 
#so
data1["PRODUCT_ORIGINAL_PRICE"]=data1["PRODUCT_ORIGINAL_PRICE"].str.replace("$","")

In [178]:
data1["PRODUCT_ORIGINAL_PRICE"].head(20) # then to convert in the

0     169.99
1     158.00
2        NaN
3     499.00
4        NaN
5     137.65
6     399.99
7        NaN
8     105.00
9     149.99
10     87.14
11     56.95
12       NaN
13    699.00
14    272.34
15     40.50
16     29.00
17     99.00
18       NaN
19       NaN
Name: PRODUCT_ORIGINAL_PRICE, dtype: object

In [180]:
data1["PRODUCT_ORIGINAL_PRICE"].value_counts().mean()

np.float64(1.0)

In [175]:
data1["PRODUCT_ORIGINAL_PRICE"].isnull().sum()

np.int64(37)

In [181]:
data1["PRODUCT_ORIGINAL_PRICE"]=data1["PRODUCT_ORIGINAL_PRICE"].fillna(method="ffill")

/var/folders/m5/pjzzzf8n62x495_tfwb87yrh0000gn/T/ipykernel_5249/3694585664.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data1["PRODUCT_ORIGINAL_PRICE"]=data1["PRODUCT_ORIGINAL_PRICE"].fillna(method="ffill")

In [184]:
data1["PRODUCT_ORIGINAL_PRICE"].value_counts() #to convert in the data type in the foloat data type

PRODUCT_ORIGINAL_PRICE
22.50     12
29.99      6
99.00      4
32.99      4
3.99       4
20.24      3
18.99      3
30.00      3
158.00     2
499.00     2
399.99     2
31.99      2
18.00      2
56.95      2
87.14      1
137.65     1
105.00     1
169.99     1
149.99     1
272.34     1
699.00     1
26.99      1
40.50      1
29.00      1
20.25      1
249.00     1
84.99      1
Name: count, dtype: int64

In [185]:
data1["PRODUCT_ORIGINAL_PRICE"]=data1["PRODUCT_ORIGINAL_PRICE"].astype(float)

In [186]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64 entries, 0 to 63
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ASIN                    64 non-null     object
 1   PRODUCT_TITLE           64 non-null     object
 2   PRODUCT_PRICE           64 non-null     float64
 3   PRODUCT_ORIGINAL_PRICE  64 non-null     float64
 4   CURRENCY                64 non-null     object
 5   PRODUCT_STAR_RATING     54 non-null     float64
 6   PRODUCT_NUM_RATINGS     64 non-null     int64
 7   DELIVERY                63 non-null     object
dtypes: float64(3), int64(1), object(4)
memory usage: 4.1+ KB

In [ ]:
# now  i am workin in the columns data1["CURRENCY"]

In [187]:
data1["CURRENCY"]  # to convert in to the indan currency

0     USD
1     USD
2     USD
3     USD
4     USD
     ...
59    USD
60    USD
61    USD
62    USD
63    USD
Name: CURRENCY, Length: 64, dtype: object

In [188]:
data1["CURRENCY"]=data1["CURRENCY"].str.replace("USD","IND")

In [189]:
data1["CURRENCY"]

0     IND
1     IND
2     IND
3     IND
4     IND
     ...
59    IND
60    IND
61    IND
62    IND
63    IND
Name: CURRENCY, Length: 64, dtype: object

In [ ]:
# now i am working in te columns data1["PRODUCT_STAR_RATING"]

In [191]:
data1["PRODUCT_STAR_RATING"].value_counts()

PRODUCT_STAR_RATING
4.7    9
4.4    7
4.2    7
4.6    5
4.8    4
4.3    4
3.9    3
4.0    3
4.5    3
3.8    2
4.1    2
3.2    2
1.8    1
3.5    1
2.6    1
Name: count, dtype: int64

In [202]:
import numpy as np
x=np.array([9,7,7,5,4,4,3,3,3,2,2,2,1,1,1])
x.mean()

np.float64(3.6)

In [205]:
np.median(x)

np.float64(3.0)

In [206]:
data1["PRODUCT_STAR_RATING"]=data1["PRODUCT_STAR_RATING"].fillna(3)

In [207]:
data1["PRODUCT_STAR_RATING"]

0     4.0
1     4.2
2     3.9
3     4.3
4     4.1
     ...
59    3.0
60    4.4
61    3.5
62    2.6
63    4.0
Name: PRODUCT_STAR_RATING, Length: 64, dtype: float64

In [212]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64 entries, 0 to 63
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ASIN                    64 non-null     object
 1   PRODUCT_TITLE           64 non-null     object
 2   PRODUCT_PRICE           64 non-null     float64
 3   PRODUCT_ORIGINAL_PRICE  64 non-null     float64
 4   CURRENCY                64 non-null     object
 5   PRODUCT_STAR_RATING     64 non-null     float64
 6   PRODUCT_NUM_RATINGS     64 non-null     int64
 7   DELIVERY                63 non-null     object
dtypes: float64(3), int64(1), object(4)
memory usage: 4.1+ KB

In [ ]:
# i am workin in the data1["PRODUCT_NUM_RATINGS"]

In [209]:
data1["PRODUCT_NUM_RATINGS"]

0      2929
1       135
2       205
3      2248
4       423
      ...
59        0
60    14471
61      270
62       12
63    48154
Name: PRODUCT_NUM_RATINGS, Length: 64, dtype: int64

In [211]:
data1["DELIVERY"].isnull().sum()

np.int64(1)

In [213]:
data1["DELIVERY"]

61            Available instantly on compatible devices
62    FREE deliveryThis item will be released on Aug...
63                                        FREE delivery
Name: DELIVERY, dtype: object

In [222]:
data1 = data1.dropna(subset=["DELIVERY"])

In [223]:
data1

,ASIN,PRODUCT_TITLE,PRODUCT_PRICE,PRODUCT_ORIGINAL_PRICE,CURRENCY,PRODUCT_STAR_RATING,PRODUCT_NUM_RATINGS,DELIVERY
0,B0BQ118F2T,Moto G Play 2023 3-Day Battery Unlocked Made f...,99.99,169.99,IND,4.0,2929,"FREE delivery Tue, Aug 6"
1,B0CTD47P22,"SAMSUNG Galaxy A15 5G (SM-156M/DSN), 128GB 6GB...",149.74,158.00,IND,4.2,135,"FREE delivery Wed, Aug 7 Only 7 left in stock ..."
2,B0CHH6X6H2,Total by Verizon | Samsung Galaxy A03s | Locke...,49.88,158.00,IND,3.9,205,"FREE delivery Tue, Aug 6"
3,B0BZ9XNBRB,Google Pixel 7a - Unlocked Android Cell Phone ...,335.00,499.00,IND,4.3,2248,FREE delivery Aug 6 - 8
4,B0CN1QSH8Q,"SAMSUNG Galaxy A15 5G A Series Cell Phone, 128...",199.99,499.00,IND,4.1,423,"FREE delivery Tue, Aug 6"
...,...,...,...,...,...,...,...,...
59,B0D6LWXK1R,Greatish Hits: I Followed My Dreams and My Dre...,34.98,22.50,IND,3.0,0,FREE delivery on $35 shipped by Amazon.This ti...
60,B0CLKQF5HR,Swan Song,14.99,30.00,IND,4.4,14471,Available instantly
61,B0BZFHK12K,Bluey: Let&#x27;s Play!,0.00,30.00,IND,3.5,270,Available instantly on compatible devices
62,B09Z7J4L6X,Xbox Wireless Controller – Sky Cipher Special ...,69.99,30.00,IND,2.6,12,FREE deliveryThis item will be released on Aug...
63,B0CT2R7199,HP DeskJet 2855e Wireless All-in-One Color Ink...,59.99,84.99,IND,4.0,48154,FREE delivery

In [224]:
pd.to_csv("after_cleaning_amaon_product",index=False)

AttributeError: module 'pandas' has no attribute 'to_csv'