In [48]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

In [49]:
data=pd.read_csv("credit_customers.csv")

In [50]:
data.head(20)

,checking_status,duration,credit_history,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,...,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
0,<0,6.0,critical/other existing credit,radio/tv,1169.0,no known savings,>=7,4.0,male single,none,...,real estate,67.0,none,own,2.0,skilled,1.0,yes,yes,good
1,0<=X<200,48.0,existing paid,radio/tv,5951.0,<100,1<=X<4,2.0,female div/dep/mar,none,...,real estate,22.0,none,own,1.0,skilled,1.0,none,yes,bad
2,no checking,12.0,critical/other existing credit,education,2096.0,<100,4<=X<7,2.0,male single,none,...,real estate,49.0,none,own,1.0,unskilled resident,2.0,none,yes,good
3,<0,42.0,existing paid,furniture/equipment,7882.0,<100,4<=X<7,2.0,male single,guarantor,...,life insurance,45.0,none,for free,1.0,skilled,2.0,none,yes,good
4,<0,24.0,delayed previously,new car,4870.0,<100,1<=X<4,3.0,male single,none,...,no known property,53.0,none,for free,2.0,skilled,2.0,none,yes,bad
5,no checking,36.0,existing paid,education,9055.0,no known savings,1<=X<4,2.0,male single,none,...,no known property,35.0,none,for free,1.0,unskilled resident,2.0,yes,yes,good
6,no checking,24.0,existing paid,furniture/equipment,2835.0,500<=X<1000,>=7,3.0,male single,none,...,life insurance,53.0,none,own,1.0,skilled,1.0,none,yes,good
7,0<=X<200,36.0,existing paid,used car,6948.0,<100,1<=X<4,2.0,male single,none,...,car,35.0,none,rent,1.0,high qualif/self emp/mgmt,1.0,yes,yes,good
8,no checking,12.0,existing paid,radio/tv,3059.0,>=1000,4<=X<7,2.0,male div/sep,none,...,real estate,61.0,none,own,1.0,unskilled resident,1.0,none,yes,good
9,0<=X<200,30.0,critical/other existing credit,new car,5234.0,<100,unemployed,4.0,male mar/wid,none,...,car,28.0,none,own,2.0,high qualif/self emp/mgmt,1.0,none,yes,bad
10,0<=X<200,12.0,existing paid,new car,1295.0,<100,<1,3.0,female div/dep/mar,none,...,car,25.0,none,rent,1.0,skilled,1.0,none,yes,bad
11,<0,48.0,existing paid,business,4308.0,<100,<1,3.0,female div/dep/mar,none,...,life insurance,24.0,none,rent,1.0,skilled,1.0,none,yes,bad
12,0<=X<200,12.0,existing paid,radio/tv,1567.0,<100,1<=X<4,1.0,female div/dep/mar,none,...,car,22.0,none,own,1.0,skilled,1.0,yes,yes,good
13,<0,24.0,critical/other existing credit,new car,1199.0,<100,>=7,4.0,male single,none,...,car,60.0,none,own,2.0,unskilled resident,1.0,none,yes,bad
14,<0,15.0,existing paid,new car,1403.0,<100,1<=X<4,2.0,female div/dep/mar,none,...,car,28.0,none,rent,1.0,skilled,1.0,none,yes,good
15,<0,24.0,existing paid,radio/tv,1282.0,100<=X<500,1<=X<4,4.0,female div/dep/mar,none,...,car,32.0,none,own,1.0,unskilled resident,1.0,none,yes,bad
16,no checking,24.0,critical/other existing credit,radio/tv,2424.0,no known savings,>=7,4.0,male single,none,...,life insurance,53.0,none,own,2.0,skilled,1.0,none,yes,good
17,<0,30.0,no credits/all paid,business,8072.0,no known savings,<1,2.0,male single,none,...,car,25.0,bank,own,3.0,skilled,1.0,none,yes,good
18,0<=X<200,24.0,existing paid,used car,12579.0,<100,>=7,4.0,female div/dep/mar,none,...,no known property,44.0,none,for free,1.0,high qualif/self emp/mgmt,1.0,yes,yes,bad
19,no checking,24.0,existing paid,radio/tv,3430.0,500<=X<1000,>=7,3.0,male single,none,...,car,31.0,none,own,1.0,skilled,2.0,yes,yes,good

In [51]:
data.head(2)

,checking_status,duration,credit_history,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,...,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
0,<0,6.0,critical/other existing credit,radio/tv,1169.0,no known savings,>=7,4.0,male single,none,...,real estate,67.0,none,own,2.0,skilled,1.0,yes,yes,good
1,0<=X<200,48.0,existing paid,radio/tv,5951.0,<100,1<=X<4,2.0,female div/dep/mar,none,...,real estate,22.0,none,own,1.0,skilled,1.0,none,yes,bad

In [52]:
data.tail(7)

,checking_status,duration,credit_history,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,...,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
993,<0,36.0,existing paid,furniture/equipment,3959.0,<100,unemployed,4.0,male single,none,...,life insurance,30.0,none,own,1.0,high qualif/self emp/mgmt,1.0,yes,yes,good
994,no checking,12.0,existing paid,new car,2390.0,no known savings,>=7,4.0,male single,none,...,car,50.0,none,own,1.0,skilled,1.0,yes,yes,good
995,no checking,12.0,existing paid,furniture/equipment,1736.0,<100,4<=X<7,3.0,female div/dep/mar,none,...,real estate,31.0,none,own,1.0,unskilled resident,1.0,none,yes,good
996,<0,30.0,existing paid,used car,3857.0,<100,1<=X<4,4.0,male div/sep,none,...,life insurance,40.0,none,own,1.0,high qualif/self emp/mgmt,1.0,yes,yes,good
997,no checking,12.0,existing paid,radio/tv,804.0,<100,>=7,4.0,male single,none,...,car,38.0,none,own,1.0,skilled,1.0,none,yes,good
998,<0,45.0,existing paid,radio/tv,1845.0,<100,1<=X<4,4.0,male single,none,...,no known property,23.0,none,for free,1.0,skilled,1.0,yes,yes,bad
999,0<=X<200,45.0,critical/other existing credit,used car,4576.0,100<=X<500,unemployed,3.0,male single,none,...,car,27.0,none,own,1.0,skilled,1.0,none,yes,good

In [53]:
data.shape

(1000, 21)

In [54]:
data.columns # first the columns convert in to the caplitalized form

Index(['checking_status', 'duration', 'credit_history', 'purpose',
       'credit_amount', 'savings_status', 'employment',
       'installment_commitment', 'personal_status', 'other_parties',
       'residence_since', 'property_magnitude', 'age', 'other_payment_plans',
       'housing', 'existing_credits', 'job', 'num_dependents', 'own_telephone',
       'foreign_worker', 'class'],
      dtype='object')

In [55]:
data_columns=[]
for i in data.columns:
    data_columns.append(i.capitalize())

In [56]:
data_columns

['Checking_status',
 'Duration',
 'Credit_history',
 'Purpose',
 'Credit_amount',
 'Savings_status',
 'Employment',
 'Installment_commitment',
 'Personal_status',
 'Other_parties',
 'Residence_since',
 'Property_magnitude',
 'Age',
 'Other_payment_plans',
 'Housing',
 'Existing_credits',
 'Job',
 'Num_dependents',
 'Own_telephone',
 'Foreign_worker',
 'Class']

In [57]:
 data1=data.copy()

In [58]:
data1.columns=data_columns

In [59]:
data1.duplicated().sum() # its not present in the duplicated values in the data set

np.int64(0)

In [60]:
#to take the info
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Checking_status         1000 non-null   object
 1   Duration                1000 non-null   float64
 2   Credit_history          1000 non-null   object
 3   Purpose                 1000 non-null   object
 4   Credit_amount           1000 non-null   float64
 5   Savings_status          1000 non-null   object
 6   Employment              1000 non-null   object
 7   Installment_commitment  1000 non-null   float64
 8   Personal_status         1000 non-null   object
 9   Other_parties           1000 non-null   object
 10  Residence_since         1000 non-null   float64
 11  Property_magnitude      1000 non-null   object
 12  Age                     1000 non-null   float64
 13  Other_payment_plans     1000 non-null   object
 14  Housing                 1000 non-null   object
 15  Existing_credits        1000 non-null   float64
 16  Job                     1000 non-null   object
 17  Num_dependents          1000 non-null   float64
 18  Own_telephone           1000 non-null   object
 19  Foreign_worker          1000 non-null   object
 20  Class                   1000 non-null   object
dtypes: float64(7), object(14)
memory usage: 164.2+ KB

In [61]:
# i toke the usable columns in the data set the other columns are deletete with in secounds
data1.columns

Index(['Checking_status', 'Duration', 'Credit_history', 'Purpose',
       'Credit_amount', 'Savings_status', 'Employment',
       'Installment_commitment', 'Personal_status', 'Other_parties',
       'Residence_since', 'Property_magnitude', 'Age', 'Other_payment_plans',
       'Housing', 'Existing_credits', 'Job', 'Num_dependents', 'Own_telephone',
       'Foreign_worker', 'Class'],
      dtype='object')

In [62]:
data1.drop(columns=['Checking_status', 'Duration', 'Credit_history', 'Purpose','Employment',
       'Installment_commitment','Other_parties','Residence_since', 'Other_payment_plans','Num_dependents'],inplace=True)

In [63]:
data1.columns

Index(['Credit_amount', 'Savings_status', 'Personal_status',
       'Property_magnitude', 'Age', 'Housing', 'Existing_credits', 'Job',
       'Own_telephone', 'Foreign_worker', 'Class'],
      dtype='object')

In [64]:
data1.head(5) # Savings_status that columns also delete the data set

,Credit_amount,Savings_status,Personal_status,Property_magnitude,Age,Housing,Existing_credits,Job,Own_telephone,Foreign_worker,Class
0,1169.0,no known savings,male single,real estate,67.0,own,2.0,skilled,yes,yes,good
1,5951.0,<100,female div/dep/mar,real estate,22.0,own,1.0,skilled,none,yes,bad
2,2096.0,<100,male single,real estate,49.0,own,1.0,unskilled resident,none,yes,good
3,7882.0,<100,male single,life insurance,45.0,for free,1.0,skilled,none,yes,good
4,4870.0,<100,male single,no known property,53.0,for free,2.0,skilled,none,yes,bad

In [65]:
data1.drop(columns=["Savings_status"],inplace=True)

In [66]:
data1.columns

Index(['Credit_amount', 'Personal_status', 'Property_magnitude', 'Age',
       'Housing', 'Existing_credits', 'Job', 'Own_telephone', 'Foreign_worker',
       'Class'],
      dtype='object')

In [67]:
data1

,Credit_amount,Personal_status,Property_magnitude,Age,Housing,Existing_credits,Job,Own_telephone,Foreign_worker,Class
0,1169.0,male single,real estate,67.0,own,2.0,skilled,yes,yes,good
1,5951.0,female div/dep/mar,real estate,22.0,own,1.0,skilled,none,yes,bad
2,2096.0,male single,real estate,49.0,own,1.0,unskilled resident,none,yes,good
3,7882.0,male single,life insurance,45.0,for free,1.0,skilled,none,yes,good
4,4870.0,male single,no known property,53.0,for free,2.0,skilled,none,yes,bad
...,...,...,...,...,...,...,...,...,...,...
995,1736.0,female div/dep/mar,real estate,31.0,own,1.0,unskilled resident,none,yes,good
996,3857.0,male div/sep,life insurance,40.0,own,1.0,high qualif/self emp/mgmt,yes,yes,good
997,804.0,male single,car,38.0,own,1.0,skilled,none,yes,good
998,1845.0,male single,no known property,23.0,for free,1.0,skilled,yes,yes,bad
999,4576.0,male single,car,27.0,own,1.0,skilled,none,yes,good

In [68]:
data1["Credit_amount"].value_counts()

Credit_amount
1275.0    3
1262.0    3
1478.0    3
1393.0    3
1258.0    3
         ..
454.0     1
1715.0    1
2520.0    1
3568.0    1
7166.0    1
Name: count, Length: 921, dtype: int64

In [69]:
# the we can cheak the duplicated value in the data1 set
data1.duplicated().sum() # in the darta set not present in the data set

np.int64(0)

In [70]:
data1.isnull().sum()

Credit_amount         0
Personal_status       0
Property_magnitude    0
Age                   0
Housing               0
Existing_credits      0
Job                   0
Own_telephone         0
Foreign_worker        0
Class                 0
dtype: int64

In [71]:
 # cheak the each and every columns  so to cheak the each columns
data1["Credit_amount"].value_counts()

Credit_amount
1275.0    3
1262.0    3
1478.0    3
1393.0    3
1258.0    3
         ..
454.0     1
1715.0    1
2520.0    1
3568.0    1
7166.0    1
Name: count, Length: 921, dtype: int64

In [72]:
data1["Personal_status"].value_counts()

Personal_status
male single           548
female div/dep/mar    310
male mar/wid           92
male div/sep           50
Name: count, dtype: int64

In [73]:
data1["Property_magnitude"].value_counts()

Property_magnitude
car                  332
real estate          282
life insurance       232
no known property    154
Name: count, dtype: int64

In [74]:
data1["Age"].value_counts()

Age
27.0    51
26.0    50
23.0    48
24.0    44
28.0    43
25.0    41
30.0    40
35.0    40
36.0    39
31.0    38
29.0    37
32.0    34
33.0    33
34.0    32
37.0    29
22.0    27
40.0    25
38.0    24
42.0    22
39.0    21
46.0    18
44.0    17
41.0    17
43.0    17
47.0    17
45.0    15
21.0    14
49.0    14
20.0    14
50.0    12
48.0    12
54.0    10
57.0     9
52.0     9
63.0     8
51.0     8
55.0     8
53.0     7
61.0     7
60.0     6
66.0     5
65.0     5
58.0     5
64.0     5
74.0     4
67.0     3
56.0     3
59.0     3
68.0     3
19.0     2
75.0     2
62.0     2
70.0     1
Name: count, dtype: int64

In [75]:
data1["Housing"].value_counts()

Housing
own         713
rent        179
for free    108
Name: count, dtype: int64

In [76]:
data1["Existing_credits"].value_counts()

Existing_credits
1.0    633
2.0    333
3.0     28
4.0      6
Name: count, dtype: int64

In [91]:
data1["Existing_credits"][8]

np.float64(1.0)

In [93]:
data1["Existing_credits"]=data1["Existing_credits"].astype(int)

In [94]:
data1["Existing_credits"][8]

np.int64(1)

In [77]:
data1["Own_telephone"].value_counts()

Own_telephone
none    596
yes     404
Name: count, dtype: int64

In [80]:
data1["Foreign_worker"].value_counts()

Foreign_worker
yes    963
no      37
Name: count, dtype: int64

In [85]:
data1["Foreign_worker"].unique() # convert into zero and one

array(['yes', 'no'], dtype=object)

In [89]:
data1["Foreign_worker"]=data1["Foreign_worker"].apply(lambda x:1 if x=="yes" else 0)

In [90]:
data1

,Credit_amount,Personal_status,Property_magnitude,Age,Housing,Existing_credits,Job,Own_telephone,Foreign_worker,Class
0,1169.0,male single,real estate,67.0,own,2.0,skilled,yes,1,1
1,5951.0,female div/dep/mar,real estate,22.0,own,1.0,skilled,none,1,0
2,2096.0,male single,real estate,49.0,own,1.0,unskilled resident,none,1,1
3,7882.0,male single,life insurance,45.0,for free,1.0,skilled,none,1,1
4,4870.0,male single,no known property,53.0,for free,2.0,skilled,none,1,0
...,...,...,...,...,...,...,...,...,...,...
995,1736.0,female div/dep/mar,real estate,31.0,own,1.0,unskilled resident,none,1,1
996,3857.0,male div/sep,life insurance,40.0,own,1.0,high qualif/self emp/mgmt,yes,1,1
997,804.0,male single,car,38.0,own,1.0,skilled,none,1,1
998,1845.0,male single,no known property,23.0,for free,1.0,skilled,yes,1,0
999,4576.0,male single,car,27.0,own,1.0,skilled,none,1,1

In [79]:
data1["Class"].value_counts()

Class
good    700
bad     300
Name: count, dtype: int64

In [82]:
data1["Class"].unique() # so onvert into the zero and one

array(['good', 'bad'], dtype=object)

In [83]:
data1["Class"]=data1["Class"].apply(lambda x:1 if x=="good" else 0)

In [84]:
data1

,Credit_amount,Personal_status,Property_magnitude,Age,Housing,Existing_credits,Job,Own_telephone,Foreign_worker,Class
0,1169.0,male single,real estate,67.0,own,2.0,skilled,yes,yes,1
1,5951.0,female div/dep/mar,real estate,22.0,own,1.0,skilled,none,yes,0
2,2096.0,male single,real estate,49.0,own,1.0,unskilled resident,none,yes,1
3,7882.0,male single,life insurance,45.0,for free,1.0,skilled,none,yes,1
4,4870.0,male single,no known property,53.0,for free,2.0,skilled,none,yes,0
...,...,...,...,...,...,...,...,...,...,...
995,1736.0,female div/dep/mar,real estate,31.0,own,1.0,unskilled resident,none,yes,1
996,3857.0,male div/sep,life insurance,40.0,own,1.0,high qualif/self emp/mgmt,yes,yes,1
997,804.0,male single,car,38.0,own,1.0,skilled,none,yes,1
998,1845.0,male single,no known property,23.0,for free,1.0,skilled,yes,yes,0
999,4576.0,male single,car,27.0,own,1.0,skilled,none,yes,1

In [ ]:
data1.to_csv("before cleaning_credit_customers.csv",index=False)