In [409]:
import numpy as np
import pandas as pd
import matplotlib as plt
data=pd.read_csv("Before_cleaning_FashionDataset.csv")

In [410]:
data

,Unnamed: 0,BrandName,Deatils,Sizes,MRP,SellPrice,Discount,Category
0,0,life,solid cotton blend collar neck womens a-line d...,"Size:Large,Medium,Small,X-Large,X-Small",Rs\n1699,849,50% off,Westernwear-Women
1,1,only,polyester peter pan collar womens blouson dres...,"Size:34,36,38,40",Rs\n3499,2449,30% off,Westernwear-Women
2,2,fratini,solid polyester blend wide neck womens regular...,"Size:Large,X-Large,XX-Large",Rs\n1199,599,50% off,Westernwear-Women
3,3,zink london,stripes polyester sweetheart neck womens dress...,"Size:Large,Medium,Small,X-Large",Rs\n2299,1379,40% off,Westernwear-Women
4,4,life,regular fit regular length denim womens jeans ...,"Size:26,28,30,32,34,36",Rs\n1699,849,50% off,Westernwear-Women
...,...,...,...,...,...,...,...,...
30753,21,swarovski,crystal stylish womens rodhium earrings,Nan,Nan,8950,Nan,Jewellery-Women
30754,22,Nan,Nan,Nan,Nan,Nan,Nan,Jewellery-Women
30755,23,jewelz,ethnic gold plated jhumki earrings,Nan,Rs\n1839,643,65% off,Jewellery-Women
30756,24,estelle,womens gold plated double line fancy white and...,Nan,Nan,2799,Nan,Jewellery-Women
30757,25,estelle,womens gold plated bridge designer mangalsutra...,Nan,Nan,1899,Nan,Jewellery-Women

In [411]:
data.head(5)

,Unnamed: 0,BrandName,Deatils,Sizes,MRP,SellPrice,Discount,Category
0,0,life,solid cotton blend collar neck womens a-line d...,"Size:Large,Medium,Small,X-Large,X-Small",Rs\n1699,849,50% off,Westernwear-Women
1,1,only,polyester peter pan collar womens blouson dres...,"Size:34,36,38,40",Rs\n3499,2449,30% off,Westernwear-Women
2,2,fratini,solid polyester blend wide neck womens regular...,"Size:Large,X-Large,XX-Large",Rs\n1199,599,50% off,Westernwear-Women
3,3,zink london,stripes polyester sweetheart neck womens dress...,"Size:Large,Medium,Small,X-Large",Rs\n2299,1379,40% off,Westernwear-Women
4,4,life,regular fit regular length denim womens jeans ...,"Size:26,28,30,32,34,36",Rs\n1699,849,50% off,Westernwear-Women

In [412]:
data.tail(4)

,Unnamed: 0,BrandName,Deatils,Sizes,MRP,SellPrice,Discount,Category
30754,22,Nan,Nan,Nan,Nan,Nan,Nan,Jewellery-Women
30755,23,jewelz,ethnic gold plated jhumki earrings,Nan,Rs\n1839,643,65% off,Jewellery-Women
30756,24,estelle,womens gold plated double line fancy white and...,Nan,Nan,2799,Nan,Jewellery-Women
30757,25,estelle,womens gold plated bridge designer mangalsutra...,Nan,Nan,1899,Nan,Jewellery-Women

In [413]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30758 entries, 0 to 30757
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  30758 non-null  int64
 1   BrandName   30758 non-null  object
 2   Deatils     30758 non-null  object
 3   Sizes       30758 non-null  object
 4   MRP         30758 non-null  object
 5   SellPrice   30758 non-null  object
 6   Discount    30758 non-null  object
 7   Category    30758 non-null  object
dtypes: int64(1), object(7)
memory usage: 1.9+ MB

In [414]:
data.isnull().sum()

Unnamed: 0    0
BrandName     0
Deatils       0
Sizes         0
MRP           0
SellPrice     0
Discount      0
Category      0
dtype: int64

In [415]:
data.drop_duplicates(inplace=True)
# first of remove the duplicate vaues

In [416]:
data

,Unnamed: 0,BrandName,Deatils,Sizes,MRP,SellPrice,Discount,Category
0,0,life,solid cotton blend collar neck womens a-line d...,"Size:Large,Medium,Small,X-Large,X-Small",Rs\n1699,849,50% off,Westernwear-Women
1,1,only,polyester peter pan collar womens blouson dres...,"Size:34,36,38,40",Rs\n3499,2449,30% off,Westernwear-Women
2,2,fratini,solid polyester blend wide neck womens regular...,"Size:Large,X-Large,XX-Large",Rs\n1199,599,50% off,Westernwear-Women
3,3,zink london,stripes polyester sweetheart neck womens dress...,"Size:Large,Medium,Small,X-Large",Rs\n2299,1379,40% off,Westernwear-Women
4,4,life,regular fit regular length denim womens jeans ...,"Size:26,28,30,32,34,36",Rs\n1699,849,50% off,Westernwear-Women
...,...,...,...,...,...,...,...,...
30752,20,shaya by caratlane,the wing woman clover charm necklace,Nan,Nan,1250,Nan,Jewellery-Women
30753,21,swarovski,crystal stylish womens rodhium earrings,Nan,Nan,8950,Nan,Jewellery-Women
30755,23,jewelz,ethnic gold plated jhumki earrings,Nan,Rs\n1839,643,65% off,Jewellery-Women
30756,24,estelle,womens gold plated double line fancy white and...,Nan,Nan,2799,Nan,Jewellery-Women
30757,25,estelle,womens gold plated bridge designer mangalsutra...,Nan,Nan,1899,Nan,Jewellery-Women

In [417]:
data.duplicated().sum() # to remove the all duplicate value

np.int64(0)

In [418]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 29427 entries, 0 to 30757
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  29427 non-null  int64
 1   BrandName   29427 non-null  object
 2   Deatils     29427 non-null  object
 3   Sizes       29427 non-null  object
 4   MRP         29427 non-null  object
 5   SellPrice   29427 non-null  object
 6   Discount    29427 non-null  object
 7   Category    29427 non-null  object
dtypes: int64(1), object(7)
memory usage: 2.0+ MB

In [419]:
data.columns # who to change the columns name in the perticular row:

Index(['Unnamed: 0', 'BrandName', 'Deatils', 'Sizes', 'MRP', 'SellPrice',
       'Discount', 'Category'],
      dtype='object')

In [420]:
data.rename(columns={'Unnamed: 0' :'S_no'},inplace=True)

In [421]:
data.columns

Index(['S_no', 'BrandName', 'Deatils', 'Sizes', 'MRP', 'SellPrice', 'Discount',
       'Category'],
      dtype='object')

In [422]:
data.rename(columns={'BrandName' :'Brand_Name'},inplace=True)

In [423]:
data.rename(columns={'SellPrice' :'Sell_Price'},inplace=True)

In [424]:
data.columns

Index(['S_no', 'Brand_Name', 'Deatils', 'Sizes', 'MRP', 'Sell_Price',
       'Discount', 'Category'],
      dtype='object')

In [425]:
 # the all columns convet into the capitilize form
data1=[]
for i in data.columns:
    data1.append(i.upper())

In [426]:
# the copy data
new_data=data.copy()

In [427]:
new_data.columns=data1

In [428]:
new_data

,S_NO,BRAND_NAME,DEATILS,SIZES,MRP,SELL_PRICE,DISCOUNT,CATEGORY
0,0,life,solid cotton blend collar neck womens a-line d...,"Size:Large,Medium,Small,X-Large,X-Small",Rs\n1699,849,50% off,Westernwear-Women
1,1,only,polyester peter pan collar womens blouson dres...,"Size:34,36,38,40",Rs\n3499,2449,30% off,Westernwear-Women
2,2,fratini,solid polyester blend wide neck womens regular...,"Size:Large,X-Large,XX-Large",Rs\n1199,599,50% off,Westernwear-Women
3,3,zink london,stripes polyester sweetheart neck womens dress...,"Size:Large,Medium,Small,X-Large",Rs\n2299,1379,40% off,Westernwear-Women
4,4,life,regular fit regular length denim womens jeans ...,"Size:26,28,30,32,34,36",Rs\n1699,849,50% off,Westernwear-Women
...,...,...,...,...,...,...,...,...
30752,20,shaya by caratlane,the wing woman clover charm necklace,Nan,Nan,1250,Nan,Jewellery-Women
30753,21,swarovski,crystal stylish womens rodhium earrings,Nan,Nan,8950,Nan,Jewellery-Women
30755,23,jewelz,ethnic gold plated jhumki earrings,Nan,Rs\n1839,643,65% off,Jewellery-Women
30756,24,estelle,womens gold plated double line fancy white and...,Nan,Nan,2799,Nan,Jewellery-Women
30757,25,estelle,womens gold plated bridge designer mangalsutra...,Nan,Nan,1899,Nan,Jewellery-Women

In [429]:
data=new_data

In [430]:
data

,S_NO,BRAND_NAME,DEATILS,SIZES,MRP,SELL_PRICE,DISCOUNT,CATEGORY
0,0,life,solid cotton blend collar neck womens a-line d...,"Size:Large,Medium,Small,X-Large,X-Small",Rs\n1699,849,50% off,Westernwear-Women
1,1,only,polyester peter pan collar womens blouson dres...,"Size:34,36,38,40",Rs\n3499,2449,30% off,Westernwear-Women
2,2,fratini,solid polyester blend wide neck womens regular...,"Size:Large,X-Large,XX-Large",Rs\n1199,599,50% off,Westernwear-Women
3,3,zink london,stripes polyester sweetheart neck womens dress...,"Size:Large,Medium,Small,X-Large",Rs\n2299,1379,40% off,Westernwear-Women
4,4,life,regular fit regular length denim womens jeans ...,"Size:26,28,30,32,34,36",Rs\n1699,849,50% off,Westernwear-Women
...,...,...,...,...,...,...,...,...
30752,20,shaya by caratlane,the wing woman clover charm necklace,Nan,Nan,1250,Nan,Jewellery-Women
30753,21,swarovski,crystal stylish womens rodhium earrings,Nan,Nan,8950,Nan,Jewellery-Women
30755,23,jewelz,ethnic gold plated jhumki earrings,Nan,Rs\n1839,643,65% off,Jewellery-Women
30756,24,estelle,womens gold plated double line fancy white and...,Nan,Nan,2799,Nan,Jewellery-Women
30757,25,estelle,womens gold plated bridge designer mangalsutra...,Nan,Nan,1899,Nan,Jewellery-Women

In [431]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 29427 entries, 0 to 30757
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   S_NO        29427 non-null  int64
 1   BRAND_NAME  29427 non-null  object
 2   DEATILS     29427 non-null  object
 3   SIZES       29427 non-null  object
 4   MRP         29427 non-null  object
 5   SELL_PRICE  29427 non-null  object
 6   DISCOUNT    29427 non-null  object
 7   CATEGORY    29427 non-null  object
dtypes: int64(1), object(7)
memory usage: 2.0+ MB

In [432]:
data.isnull().sum()

S_NO          0
BRAND_NAME    0
DEATILS       0
SIZES         0
MRP           0
SELL_PRICE    0
DISCOUNT      0
CATEGORY      0
dtype: int64

In [433]:
con=0
data["BRAND_NAME"]
for i in data["BRAND_NAME"]:
    if(i=='Nan'):
        con=con+1
print(con)

7

In [434]:
data["BRAND_NAME"].value_counts().iloc[174:190]

BRAND_NAME
moschino               8
colour me              7
yves saint laurent     7
nike                   7
Nan                    7
duke                   7
real effect            7
elizabeth arden        6
yves rocher            6
embark                 6
stoln accessories      5
abercrombie & fitch    5
marc jacobs            5
xylys                  5
havaianas              5
estee lauder           5
Name: count, dtype: int64

In [435]:
# to drop the Nan value
data["BRAND_NAME"] = data["BRAND_NAME"].replace("Nan", np.nan)

In [436]:
data.isnull().sum()

S_NO          0
BRAND_NAME    7
DEATILS       0
SIZES         0
MRP           0
SELL_PRICE    0
DISCOUNT      0
CATEGORY      0
dtype: int64

In [437]:
data["BRAND_NAME"].isnull().sum()

np.int64(7)

In [438]:
 # to remove the null value 
data.dropna(subset=["BRAND_NAME"],inplace=True)

In [439]:
data.isnull().sum()

S_NO          0
BRAND_NAME    0
DEATILS       0
SIZES         0
MRP           0
SELL_PRICE    0
DISCOUNT      0
CATEGORY      0
dtype: int64

In [440]:
 # knw i am working in the in the columns data["DEATILS"]

In [441]:
data["DEATILS"].value_counts()

DEATILS
synthetic womens casual sandals - black                                                                     35
alloy metal gold color western womens earrings                                                              27
solid zari silk blend festive wear womens regular saree - black                                             24
structured zari silk blend festive wear womens regular saree - green                                        24
structured zari silk blend festive wear womens regular saree - pink                                         23
                                                                                                            ..
the wing woman clover charm necklace                                                                         1
sterling silver oval turquoise ear studs                                                                     1
womens pearl golden drops                                                                                    1
nine pieces combo fashion non-precious metal base earrings                                                   1
womens metallic gold statement multilayered chain with bar and ring lock detail western necklace - multi     1
Name: count, Length: 23876, dtype: int64

In [442]:
con=0
data["DEATILS"]
for i in data["DEATILS"]:
    if(i=='Nan'):
        con=con+1
print(con) 
 #the columns no present in the Nan value

0

In [443]:
 # know i am working the columns name  data["SIZES"]

In [444]:
data["SIZES"].head(90)

0     Size:Large,Medium,Small,X-Large,X-Small
1                            Size:34,36,38,40
2                 Size:Large,X-Large,XX-Large
3             Size:Large,Medium,Small,X-Large
4                      Size:26,28,30,32,34,36
                       ...
88                        Size:10,12,14,16,18
89          Size:Large,Medium,X-Large,X-Small
90                              Size:28,30,32
91            Size:Large,Medium,Small,X-Small
92                     Size:26,28,30,32,34,36
Name: SIZES, Length: 90, dtype: object

In [445]:
data["SIZES"].tail(90) # the Nan value I thing fill in the string formate that why not showing in the Nan value

30663    Nan
30664    Nan
30665    Nan
30666    Nan
30667    Nan
        ...
30752    Nan
30753    Nan
30755    Nan
30756    Nan
30757    Nan
Name: SIZES, Length: 90, dtype: object

In [446]:
data["SIZES"].value_counts()

SIZES
Nan                                                                                   6194
Size:Large,Medium,Small,X-Large,X-Small                                               1970
Size:Large,Medium,Small,X-Large                                                       1615
Size:Large,Medium,Small,X-Large,X-Small,XX-Large                                      1505
Size:Large,Medium,Small,X-Large,XX-Large                                              1441
                                                                                      ...
Size:35,36,38                                                                            1
Size:35,36,38,39                                                                         1
Size:3,8                                                                                 1
Size:36,41                                                                               1
Size:34-B,34-C,34-D,34-DD,36-D,36-DD,38-D,40-B,40-C,40-D,40-DD,42-B,42-C,42-D,44-D       1
Name: count, Length: 1172, dtype: int64

In [447]:
count=0
for i in data["SIZES"]:
    if(i=="Nan"):
        count+=1
print(count)

6194

In [448]:
data["SIZES"].isnull().sum()

np.int64(0)

In [449]:
data["SIZES"]=data["SIZES"].replace("Nan",np.nan)

In [450]:
data["SIZES"].isnull().sum()

np.int64(6194)

In [451]:
data.isnull().sum()

S_NO             0
BRAND_NAME       0
DEATILS          0
SIZES         6194
MRP              0
SELL_PRICE       0
DISCOUNT         0
CATEGORY         0
dtype: int64

In [452]:
print(data["SIZES"].value_counts().median())
print(data["SIZES"].value_counts().mean())
print(data["SIZES"].value_counts().mode())

2.0
19.834329632792485
0    1
Name: count, dtype: int64

In [453]:
# to fill the data in the null value
data["SIZES"].value_counts()

SIZES
Size:Large,Medium,Small,X-Large,X-Small               1970
Size:Large,Medium,Small,X-Large                       1615
Size:Large,Medium,Small,X-Large,X-Small,XX-Large      1505
Size:Large,Medium,Small,X-Large,XX-Large              1441
Size:Large,Medium,Small,X-Large,XX-Large,XXX-Large     738
                                                      ...
Size:35,36,37,38,40                                      1
Size:2,3,4,6                                             1
Size:5,6,11                                              1
Size:3,4,6                                               1
Size:7.5,8.5                                             1
Name: count, Length: 1171, dtype: int64

In [454]:
data["SIZES"].value_counts().iloc[100:50]

Series([], Name: count, dtype: int64)

In [455]:
data["SIZES"].isnull().sum()

np.int64(6194)

In [456]:
data["SIZES"]=data["SIZES"].fillna("Size:Large,Medium,X-Large,X-Small,XX-Large")

In [457]:
data.isnull().sum()

S_NO          0
BRAND_NAME    0
DEATILS       0
SIZES         0
MRP           0
SELL_PRICE    0
DISCOUNT      0
CATEGORY      0
dtype: int64

In [458]:
# know i am working in the columns data["MRP"]

In [459]:
data["MRP"].isnull().sum()

np.int64(0)

In [460]:
cout=0
for i in data["MRP"]:
    if(i=="Nan"):
        cout=cout+1
print(cout)

7007

In [461]:
#  3 the columns data inthe given in the Nan value  the first convert into the 0 form so convert the nan

In [462]:
data["MRP"]=data["MRP"].str.replace("Nan" ,"949")

In [463]:
data["MRP"].isnull().sum()

np.int64(0)

In [464]:
data["MRP"].value_counts()

MRP
949          7007
Rs\n1499      925
Rs\n1999      918
Rs\n999       876
Rs\n1299      854
             ...
Rs\n12100       1
Rs\n17300       1
Rs\n5100        1
Rs\n680         1
Rs\n1059        1
Name: count, Length: 1097, dtype: int64

In [465]:
data["MRP"]

0        Rs\n1699
1        Rs\n3499
2        Rs\n1199
3        Rs\n2299
4        Rs\n1699
           ...
30752         949
30753         949
30755    Rs\n1839
30756         949
30757         949
Name: MRP, Length: 29420, dtype: object

In [466]:
data["MRP"].value_counts()

MRP
949          7007
Rs\n1499      925
Rs\n1999      918
Rs\n999       876
Rs\n1299      854
             ...
Rs\n12100       1
Rs\n17300       1
Rs\n5100        1
Rs\n680         1
Rs\n1059        1
Name: count, Length: 1097, dtype: int64

In [468]:
data["MRP"].value_counts()
print(data["MRP"][4])

Rs
1699

In [469]:
data["MRP"]=data["MRP"].str.replace("Rs\n","",regex=False)

In [470]:
data["MRP"]=data["MRP"].fillna("0")

In [471]:
print(data["MRP"].value_counts().mean())
print(data["MRP"].value_counts().median())
print(data["MRP"].value_counts().median())

26.843065693430656
2.0
2.0

In [472]:
data["MRP"].value_counts().iloc[110:130]

MRP
1298    28
7500    28
9495    27
3700    27
3495    27
849     26
3990    26
2195    26
1300    26
5495    25
1294    24
1494    24
2890    24
4199    24
6995    24
1590    23
398     23
4495    23
1150    23
6499    23
Name: count, dtype: int64

In [474]:
data["MRP"].value_counts()

MRP
949      7033
1499      925
1999      918
999       876
1299      854
         ...
12100       1
17300       1
5100        1
680         1
1059        1
Name: count, Length: 1096, dtype: int64

In [477]:
data["MRP"][8] # to type convertion of the data

np.int64(2099)

In [476]:
data["MRP"]=data["MRP"].astype(int)

In [479]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 29420 entries, 0 to 30757
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   S_NO        29420 non-null  int64
 1   BRAND_NAME  29420 non-null  object
 2   DEATILS     29420 non-null  object
 3   SIZES       29420 non-null  object
 4   MRP         29420 non-null  int64
 5   SELL_PRICE  29420 non-null  object
 6   DISCOUNT    29420 non-null  object
 7   CATEGORY    29420 non-null  object
dtypes: int64(2), object(6)
memory usage: 3.0+ MB

In [483]:
data["SELL_PRICE"].head(20)

0      849
1     2449
2      599
3     1379
4      849
5     1615
6      649
7      649
8      839
9      599
10     749
11     499
12     749
13     299
14     499
15     599
16     299
17     649
18     799
19     999
Name: SELL_PRICE, dtype: object

In [482]:
data["SELL_PRICE"].tail(20)

30737    4199
30738    1699
30739    2089
30740     149
30741    2564
30742    4195
30743    1614
30744     424
30745    1299
30746     608
30747     399
30748     468
30749     381
30750    1030
30751    8950
30752    1250
30753    8950
30755     643
30756    2799
30757    1899
Name: SELL_PRICE, dtype: object

In [484]:
data["SELL_PRICE"].value_counts()

SELL_PRICE
499      798
999      780
599      668
899      609
799      601
        ...
5515       1
7700       1
6413       1
3059       1
15500      1
Name: count, Length: 2045, dtype: int64

In [486]:
type(data["SELL_PRICE"][9])

str

In [489]:
count=0
for i in data["SELL_PRICE"]:
    if(i=="Nan"):
        count=count+1
print(count)

0

In [490]:
data["SELL_PRICE"]=data["SELL_PRICE"].astype(int)

In [491]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 29420 entries, 0 to 30757
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   S_NO        29420 non-null  int64
 1   BRAND_NAME  29420 non-null  object
 2   DEATILS     29420 non-null  object
 3   SIZES       29420 non-null  object
 4   MRP         29420 non-null  int64
 5   SELL_PRICE  29420 non-null  int64
 6   DISCOUNT    29420 non-null  object
 7   CATEGORY    29420 non-null  object
dtypes: int64(3), object(5)
memory usage: 3.0+ MB

In [ ]:
# know i am working in the columns data["DISCOUNT"]

In [498]:
data["DISCOUNT"]

0        50% off
1        30% off
2        50% off
3        40% off
4        50% off
          ...
30752        Nan
30753        Nan
30755    65% off
30756        Nan
30757        Nan
Name: DISCOUNT, Length: 29420, dtype: object

In [500]:
data["DISCOUNT"].isnull().sum()

np.int64(0)

In [501]:
count=0
for i in data["DISCOUNT"]:
    if(i=="Nan"):
        count=count+1
print(count)

7007

In [503]:
data["DISCOUNT"].value_counts().mean()

np.float64(445.75757575757575)

In [505]:
data["DISCOUNT"].value_counts()

DISCOUNT
50% off    7557
Nan        7007
30% off    2749
60% off    2634
40% off    2186
           ...
22% off       1
66% off       1
77% off       1
28% off       1
36% off       1
Name: count, Length: 66, dtype: int64

In [507]:
data["DISCOUNT"].value_counts().iloc[9:20]

DISCOUNT
45% off    523
10% off    497
25% off    340
35% off    304
5% off     254
75% off    202
15% off     84
80% off     71
67% off     48
69% off     43
41% off     32
Name: count, dtype: int64

In [508]:
data["DISCOUNT"]=data["DISCOUNT"].str.replace("Nan","10% off")

In [510]:
data["DISCOUNT"][8]

'60% off'

In [511]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 29420 entries, 0 to 30757
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   S_NO        29420 non-null  int64
 1   BRAND_NAME  29420 non-null  object
 2   DEATILS     29420 non-null  object
 3   SIZES       29420 non-null  object
 4   MRP         29420 non-null  int64
 5   SELL_PRICE  29420 non-null  int64
 6   DISCOUNT    29420 non-null  object
 7   CATEGORY    29420 non-null  object
dtypes: int64(3), object(5)
memory usage: 3.0+ MB

In [ ]:
# now i am working in the column data["CATEGORY"]

In [514]:
data["CATEGORY"].value_counts()

CATEGORY
Westernwear-Women           9961
Indianwear-Women            9857
Lingerie&Nightwear-Women    3221
Footwear-Women              2465
Watches-Women               1724
Jewellery-Women             1717
Fragrance-Women              475
Name: count, dtype: int64

In [515]:
count=0
for i in data["CATEGORY"]:
    if(i=="Nan"):
        count=count+1
print(count)

0

In [516]:
# finaly the row data clean the no of rows
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 29420 entries, 0 to 30757
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   S_NO        29420 non-null  int64
 1   BRAND_NAME  29420 non-null  object
 2   DEATILS     29420 non-null  object
 3   SIZES       29420 non-null  object
 4   MRP         29420 non-null  int64
 5   SELL_PRICE  29420 non-null  int64
 6   DISCOUNT    29420 non-null  object
 7   CATEGORY    29420 non-null  object
dtypes: int64(3), object(5)
memory usage: 3.0+ MB

In [ ]:
 # the lost of no of row data aprox 6000 data

In [517]:
data.to_csv("FashionDataset_code_data_After cleaning.csv",index=False)