In [141]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

data=pd.read_csv("zomato_before_cleaning_data.csv")

In [142]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51717 entries, 0 to 51716
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   url                          51717 non-null  object
 1   address                      51717 non-null  object
 2   name                         51717 non-null  object
 3   online_order                 51717 non-null  object
 4   book_table                   51717 non-null  object
 5   rate                         43942 non-null  object
 6   votes                        51717 non-null  int64
 7   phone                        50509 non-null  object
 8   location                     51696 non-null  object
 9   rest_type                    51490 non-null  object
 10  dish_liked                   23639 non-null  object
 11  cuisines                     51672 non-null  object
 12  approx_cost(for two people)  51371 non-null  object
 13  reviews_list                 51717 non-null  object
 14  menu_item                    51717 non-null  object
 15  listed_in(type)              51717 non-null  object
 16  listed_in(city)              51717 non-null  object
dtypes: int64(1), object(16)
memory usage: 6.7+ MB

In [143]:
data.shape # the number of row and the number of the column

(51717, 17)

In [144]:
data.head(90)

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,https://www.zomato.com/bangalore/the-big-o-bak...,"45/12, 4th Cross, 10th Main, Gururaja Layout, ...",The Big O Bakes,No,No,4.0/5,66,+91 9845216137,Banashankari,Bakery,NaN,"Bakery, Desserts",300,"[('Rated 5.0', 'RATED\n You get the best dess...",[],Delivery,Banashankari
86,https://www.zomato.com/bangalore/meghana-foods...,"52, 1st Floor, 33rd Cross, 4th Block, Jayanaga...",Meghana Foods,Yes,No,4.4/5,4401,080 49653564,Jayanagar,Casual Dining,"Chicken Boneless Biryani, Hyderabadi Biryani, ...","Biryani, North Indian, Chinese",600,"[('Rated 2.0', 'RATED\n Meghana foods!!! The ...",[],Delivery,Banashankari
87,https://www.zomato.com/bangalore/krishna-sagar...,"38, 22nd Main, 22nd Cross, Opposite BDA, 2nd S...",Krishna Sagar,No,No,3.5/5,31,+91 8892752997\r\n+91 7204780429,Banashankari,Quick Bites,NaN,North Indian,200,"[('Rated 1.0', 'RATED\n Worst experience with...",[],Delivery,Banashankari
88,https://www.zomato.com/bangalore/dessert-rose-...,"1/34, 3rd Cross Road, Kathriguppe IV Phase, Ba...",Dessert Rose,No,No,3.5/5,7,+91 7829604777,Banashankari,Dessert Parlor,NaN,Desserts,500,"[('Rated 5.0', 'RATED\n Tried the rose and ch...",[],Delivery,Banashankari
89,https://www.zomato.com/bangalore/chickpet-donn...,"480/A, 50 feet road, Nagendra block, Near PES ...",Chickpet Donne Biryani House,No,No,3.7/5,21,+91 9482020323\r\n080 68888834,Banashankari,Quick Bites,NaN,Biryani,250,"[('Rated 4.0', 'RATED\n One of the famous bir...",[],Delivery,Banashankari

In [145]:
data.tail(10)

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
51707,https://www.zomato.com/bangalore/m-bar-bengalu...,"Bengaluru Marriott Hotel, 75, 8th Road, EPIP A...",M Bar - Bengaluru Marriott Hotel Whitefield,No,No,3.9 /5,77,080 49435000,Whitefield,"Fine Dining, Bar",Rooftop Ambience,Finger Food,"2,000","[('Rated 4.0', 'RATED\n Went there post dinne...",[],Pubs and bars,Whitefield
51708,https://www.zomato.com/bangalore/keys-cafe-key...,"Keys Hotel, 6, 1st Phase Industrial Area, Near...",Keys Cafe - Keys Hotel,No,No,2.8 /5,161,080 39451000\n+91 8884038484,Whitefield,"Casual Dining, Bar","Salads, Coffee, Breakfast Buffet, Halwa, Chick...","Chinese, Continental, North Indian","1,200","[('Rated 3.0', 'RATED\n Place is good not tha...",[],Pubs and bars,Whitefield
51709,https://www.zomato.com/bangalore/the-farm-hous...,"136, SAP Labs India, KIADB Export Promotion In...",The Farm House Bar n Grill,No,No,3.7 /5,34,+91 9980121279\n+91 9900240646,Whitefield,"Casual Dining, Bar",NaN,"North Indian, Continental",800,"[('Rated 4.0', 'RATED\n Ambience- Big and spa...",[],Pubs and bars,Whitefield
51710,https://www.zomato.com/bangalore/topsy-turvey-...,"2E2, 4th Cross Road, Devasandra Industrial Est...",Topsy Turvey,No,No,NaN,0,+91 9148155994,Whitefield,Bar,NaN,Finger Food,900,"[('Rated 4.0', ""RATED\n A divine joint for Fl...",[],Pubs and bars,Whitefield
51711,https://www.zomato.com/bangalore/bhagini-2-whi...,"139/C1, Next To GR Tech Park, Pattandur Agraha...",Bhagini,No,No,2.5 /5,81,080 65951222,Whitefield,"Casual Dining, Bar","Biryani, Andhra Meal","Andhra, South Indian, Chinese, North Indian",800,"[('Rated 4.0', 'RATED\n A fine place to chill...",[],Pubs and bars,Whitefield
51712,https://www.zomato.com/bangalore/best-brews-fo...,"Four Points by Sheraton Bengaluru, 43/3, White...",Best Brews - Four Points by Sheraton Bengaluru...,No,No,3.6 /5,27,080 40301477,Whitefield,Bar,NaN,Continental,"1,500","[('Rated 5.0', ""RATED\n Food and service are ...",[],Pubs and bars,Whitefield
51713,https://www.zomato.com/bangalore/vinod-bar-and...,"Number 10, Garudachar Palya, Mahadevapura, Whi...",Vinod Bar And Restaurant,No,No,NaN,0,+91 8197675843,Whitefield,Bar,NaN,Finger Food,600,[],[],Pubs and bars,Whitefield
51714,https://www.zomato.com/bangalore/plunge-sherat...,Sheraton Grand Bengaluru Whitefield Hotel & Co...,Plunge - Sheraton Grand Bengaluru Whitefield H...,No,No,NaN,0,NaN,Whitefield,Bar,NaN,Finger Food,"2,000",[],[],Pubs and bars,Whitefield
51715,https://www.zomato.com/bangalore/chime-sherato...,Sheraton Grand Bengaluru Whitefield Hotel & Co...,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,236,080 49652769,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,"2,500","[('Rated 4.0', 'RATED\n Nice and friendly pla...",[],Pubs and bars,Whitefield
51716,https://www.zomato.com/bangalore/the-nest-the-...,"ITPL Main Road, KIADB Export Promotion Industr...",The Nest - The Den Bengaluru,No,No,3.4 /5,13,+91 8071117272,"ITPL Main Road, Whitefield","Bar, Casual Dining",NaN,"Finger Food, North Indian, Continental","1,500","[('Rated 5.0', 'RATED\n Great ambience , look...",[],Pubs and bars,Whitefield

In [146]:
data.isnull().sum()

url                                0
address                            0
name                               0
online_order                       0
book_table                         0
rate                            7775
votes                              0
phone                           1208
location                          21
rest_type                        227
dish_liked                     28078
cuisines                          45
approx_cost(for two people)      346
reviews_list                       0
menu_item                          0
listed_in(type)                    0
listed_in(city)                    0
dtype: int64

In [147]:
data.columns

Index(['url', 'address', 'name', 'online_order', 'book_table', 'rate', 'votes',
       'phone', 'location', 'rest_type', 'dish_liked', 'cuisines',
       'approx_cost(for two people)', 'reviews_list', 'menu_item',
       'listed_in(type)', 'listed_in(city)'],
      dtype='object')

In [148]:
# the columns convert into (upper case ,lower case) so i cose the upper case
data1=[]
for i in data.columns:
    data1.append(i.upper())

In [149]:
copy1=data.copy()

In [150]:
copy1.columns=data1

In [151]:
copy1 # the columns convert into upper case  so

,URL,ADDRESS,NAME,ONLINE_ORDER,BOOK_TABLE,RATE,VOTES,PHONE,LOCATION,REST_TYPE,DISH_LIKED,CUISINES,APPROX_COST(FOR TWO PEOPLE),REVIEWS_LIST,MENU_ITEM,LISTED_IN(TYPE),LISTED_IN(CITY)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51712,https://www.zomato.com/bangalore/best-brews-fo...,"Four Points by Sheraton Bengaluru, 43/3, White...",Best Brews - Four Points by Sheraton Bengaluru...,No,No,3.6 /5,27,080 40301477,Whitefield,Bar,NaN,Continental,"1,500","[('Rated 5.0', ""RATED\n Food and service are ...",[],Pubs and bars,Whitefield
51713,https://www.zomato.com/bangalore/vinod-bar-and...,"Number 10, Garudachar Palya, Mahadevapura, Whi...",Vinod Bar And Restaurant,No,No,NaN,0,+91 8197675843,Whitefield,Bar,NaN,Finger Food,600,[],[],Pubs and bars,Whitefield
51714,https://www.zomato.com/bangalore/plunge-sherat...,Sheraton Grand Bengaluru Whitefield Hotel & Co...,Plunge - Sheraton Grand Bengaluru Whitefield H...,No,No,NaN,0,NaN,Whitefield,Bar,NaN,Finger Food,"2,000",[],[],Pubs and bars,Whitefield
51715,https://www.zomato.com/bangalore/chime-sherato...,Sheraton Grand Bengaluru Whitefield Hotel & Co...,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,236,080 49652769,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,"2,500","[('Rated 4.0', 'RATED\n Nice and friendly pla...",[],Pubs and bars,Whitefield
51716,https://www.zomato.com/bangalore/the-nest-the-...,"ITPL Main Road, KIADB Export Promotion Industr...",The Nest - The Den Bengaluru,No,No,3.4 /5,13,+91 8071117272,"ITPL Main Road, Whitefield","Bar, Casual Dining",NaN,"Finger Food, North Indian, Continental","1,500","[('Rated 5.0', 'RATED\n Great ambience , look...",[],Pubs and bars,Whitefield

In [152]:
copy1.columns

Index(['URL', 'ADDRESS', 'NAME', 'ONLINE_ORDER', 'BOOK_TABLE', 'RATE', 'VOTES',
       'PHONE', 'LOCATION', 'REST_TYPE', 'DISH_LIKED', 'CUISINES',
       'APPROX_COST(FOR TWO PEOPLE)', 'REVIEWS_LIST', 'MENU_ITEM',
       'LISTED_IN(TYPE)', 'LISTED_IN(CITY)'],
      dtype='object')

In [153]:
copy1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51717 entries, 0 to 51716
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   URL                          51717 non-null  object
 1   ADDRESS                      51717 non-null  object
 2   NAME                         51717 non-null  object
 3   ONLINE_ORDER                 51717 non-null  object
 4   BOOK_TABLE                   51717 non-null  object
 5   RATE                         43942 non-null  object
 6   VOTES                        51717 non-null  int64
 7   PHONE                        50509 non-null  object
 8   LOCATION                     51696 non-null  object
 9   REST_TYPE                    51490 non-null  object
 10  DISH_LIKED                   23639 non-null  object
 11  CUISINES                     51672 non-null  object
 12  APPROX_COST(FOR TWO PEOPLE)  51371 non-null  object
 13  REVIEWS_LIST                 51717 non-null  object
 14  MENU_ITEM                    51717 non-null  object
 15  LISTED_IN(TYPE)              51717 non-null  object
 16  LISTED_IN(CITY)              51717 non-null  object
dtypes: int64(1), object(16)
memory usage: 6.7+ MB

In [154]:
copy1.isnull().sum()

URL                                0
ADDRESS                            0
NAME                               0
ONLINE_ORDER                       0
BOOK_TABLE                         0
RATE                            7775
VOTES                              0
PHONE                           1208
LOCATION                          21
REST_TYPE                        227
DISH_LIKED                     28078
CUISINES                          45
APPROX_COST(FOR TWO PEOPLE)      346
REVIEWS_LIST                       0
MENU_ITEM                          0
LISTED_IN(TYPE)                    0
LISTED_IN(CITY)                    0
dtype: int64

In [155]:
copy1["URL"].value_counts()

URL
https://www.zomato.com/bangalore/the-nest-the-den-bengaluru-itpl-main-road-whitefield-bangalore?context=eyJzZSI6eyJlIjpbIjU4MzU0IiwiMTg3NDExMjkiLCIxODY2MTA0MCIsIjE4NjYxMDg0IiwxODY5MDgzN10sInQiOiJQdWJzICZhbXA7IEJhcnMgaW4gV2hpdGVmaWVsZCJ9fQ==                                                                                        1
https://www.zomato.com/bangalore/jalsa-banashankari?context=eyJzZSI6eyJlIjpbNTg2OTQsIjE4Mzc1NDc0IiwiNTkwOTAiLCIxODM4Mjk0NCIsIjE4MjI0Njc2IiwiNTkyODkiLCIxODM3MzM4NiJdLCJ0IjoiUmVzdGF1cmFudHMgaW4gQmFuYXNoYW5rYXJpIHNlcnZpbmcgQnVmZmV0In19                                                                                                1
https://www.zomato.com/bangalore/spice-elephant-banashankari?context=eyJzZSI6eyJlIjpbIjU4Njk0IiwxODM3NTQ3NCwiNTkwOTAiLCIxODM4Mjk0NCIsIjE4MjI0Njc2IiwiNTkyODkiLCIxODM3MzM4NiJdLCJ0IjoiUmVzdGF1cmFudHMgaW4gQmFuYXNoYW5rYXJpIHNlcnZpbmcgQnVmZmV0In19                                                                                       1
https://www.zomato.com/SanchurroBangalore?context=eyJzZSI6eyJlIjpbIjU4Njk0IiwiMTgzNzU0NzQiLDU5MDkwLCIxODM4Mjk0NCIsIjE4MjI0Njc2IiwiNTkyODkiLCIxODM3MzM4NiJdLCJ0IjoiUmVzdGF1cmFudHMgaW4gQmFuYXNoYW5rYXJpIHNlcnZpbmcgQnVmZmV0In19                                                                                                          1
https://www.zomato.com/bangalore/addhuri-udupi-bhojana-banashankari?context=eyJzZSI6eyJlIjpbIjU4Njk0IiwiMTgzNzU0NzQiLCI1OTA5MCIsMTgzODI5NDQsIjE4MjI0Njc2IiwiNTkyODkiLCIxODM3MzM4NiJdLCJ0IjoiUmVzdGF1cmFudHMgaW4gQmFuYXNoYW5rYXJpIHNlcnZpbmcgQnVmZmV0In19                                                                                1
                                                                                                                                                                                                                                                                                                                                       ..
https://www.zomato.com/bangalore/smacznego-banashankari?context=eyJzZSI6eyJlIjpbIjE4NTY1Njc5IiwiMTg1OTMwNDQiLDE4MTQ4OTQxLCIxODQ3MDc3MSIsIjE4NzE2MDYxIiwiMTg2MzI5NzciLCIxODIwMjk5NyIsIjU5MDkwIiwiMTg1NTkyMTEiLCIxODMyMzYzOSIsIjE4NTc0Mjc3IiwiMTg3MjM0OTQiLCIxODg2NzEyMiJdLCJ0IjoiQ2FmXHUwMGU5cyBhbmQgRGVsaXMgaW4gQmFuYXNoYW5rYXJpIn19    1
https://www.zomato.com/bangalore/penthouse-cafe-banashankari?context=eyJzZSI6eyJlIjpbIjE4NTY1Njc5IiwxODU5MzA0NCwiMTgxNDg5NDEiLCIxODQ3MDc3MSIsIjE4NzE2MDYxIiwiMTg2MzI5NzciLCIxODIwMjk5NyIsIjU5MDkwIiwiMTg1NTkyMTEiLCIxODMyMzYzOSIsIjE4NTc0Mjc3IiwiMTg3MjM0OTQiXSwidCI6IkNhZlx1MDBlOXMgYW5kIERlbGlzIGluIEJhbmFzaGFua2FyaSJ9fQ==           1
https://www.zomato.com/bangalore/onesta-banashankari?context=eyJzZSI6eyJlIjpbMTg1NjU2NzksIjE4NTkzMDQ0IiwiMTgxNDg5NDEiLCIxODQ3MDc3MSIsIjE4NzE2MDYxIiwiMTg2MzI5NzciLCIxODIwMjk5NyIsIjU5MDkwIiwiMTg1NTkyMTEiLCIxODMyMzYzOSIsIjE4NTc0Mjc3Il0sInQiOiJDYWZcdTAwZTlzIGFuZCBEZWxpcyBpbiBCYW5hc2hhbmthcmkifX0=                                   1
https://www.zomato.com/bangalore/rosewood-international-hotel-bar-restaurant-mysore-road-bangalore?context=eyJzZSI6eyJlIjpbIjU5MDkwIiwiMTgzODI5NDQiLCIxODIyNDY3NiIsIjU5Mjg5IiwxODM3MzM4Nl0sInQiOiJSZXN0YXVyYW50cyBpbiBCYW5hc2hhbmthcmkgc2VydmluZyBCdWZmZXQifX0=                                                                         1
https://www.zomato.com/bangalore/timepass-dinner-basavanagudi?context=eyJzZSI6eyJlIjpbIjE4Mzc1NDc0IiwiNTkwOTAiLCIxODM4Mjk0NCIsIjE4MjI0Njc2Iiw1OTI4OSwiMTgzNzMzODYiXSwidCI6IlJlc3RhdXJhbnRzIGluIEJhbmFzaGFua2FyaSBzZXJ2aW5nIEJ1ZmZldCJ9fQ==                                                                                              1
Name: count, Length: 51717, dtype: int64

In [156]:
copy1["ADDRESS"].value_counts().iloc[128:150]

ADDRESS
2, Dickenson Road, FM Cariappa Colony, Sivanchetti Gardens, Commercial Street, Bangalore         19
307, Thimmaiah Rd, Govinda Chetty Colony, Shivajinagar, Bangalore                                19
The Ambara, 22, Annaswami Mudaliar Road, Near Ulsoor Lake, Ulsoor, Bangalore                     19
14, Patel Medicals, 7th Main, BTM 2nd Stage, BTM, Bangalore                                      19
42, 1st Main, Koramangala 1st Block, Bangalore                                                   19
1086/A, Twin Tulips, 18th Cross, 14th Main Road, Sector 3, HSR, Bangalore                        19
28, Ground Floor, SG Palaya, Behind Chirst College, BTM, Bangalore                               18
122/B, Jyothi Nivas Road, 5th Block, Koramangala 5th Block, Bangalore                            18
Money Chambers Double Road, Shanti Nagar, Bangalore                                              18
30, SG Palya Main Road, Madiwala, BTM, Bangalore                                                 18
22, Ulsoor Road, (ground floor of Sunrise Chambers), Bangalore                                   18
1136, Above Andhra Bank, 17th Cross Road, Muneswara Nagar, Sector 7, HSR, Bangalore              18
31, Sree Yellamma Temple Street, Ulsoor, Bangalore                                               18
365, B 5, B.D.A. Flat, Austin Tower, Richmond Road, Bangalore                                    18
The Hatworks Boulevard, 32, Cunningham Road, Bangalore                                           18
21, Prestige Copper Arch, Next to Safina Plaza, Infantry Road, Bangalore                         18
G-18, Kedia Arcade, 92, Infantry Road, Bangalore                                                 18
36, Vittal Mallya Road, Lavelle Road, Bangalore                                                  18
3rd Floor, 15, Madras Bank Road/ Museum Road, Above NEXA Showroom, Bangalore                     18
4th Floor, Building 9, Halcyon Complex, St. Marks Road, Bangalore                                18
91, Jyothi Nivas College Road, Koramangala 5th Block, Bangalore                                  18
Hotel Bangalore International, 2A-2B, Crescent Road, Highgrounds, Race Course Road, Bangalore    18
Name: count, dtype: int64

In [157]:
copy1.columns

Index(['URL', 'ADDRESS', 'NAME', 'ONLINE_ORDER', 'BOOK_TABLE', 'RATE', 'VOTES',
       'PHONE', 'LOCATION', 'REST_TYPE', 'DISH_LIKED', 'CUISINES',
       'APPROX_COST(FOR TWO PEOPLE)', 'REVIEWS_LIST', 'MENU_ITEM',
       'LISTED_IN(TYPE)', 'LISTED_IN(CITY)'],
      dtype='object')

In [158]:
# to the ccolumn devided into the two part no of row form 
columns_keep=['NAME','ONLINE_ORDER','BOOK_TABLE','RATE','DISH_LIKED','APPROX_COST(FOR TWO PEOPLE)']
columns_drops=['URL','ADDRESS','VOTES','PHONE', 'LOCATION', 'REST_TYPE','CUISINES', 'REVIEWS_LIST', 'MENU_ITEM','LISTED_IN(TYPE)', 'LISTED_IN(CITY)']

In [159]:
copy1.isnull().sum()

URL                                0
ADDRESS                            0
NAME                               0
ONLINE_ORDER                       0
BOOK_TABLE                         0
RATE                            7775
VOTES                              0
PHONE                           1208
LOCATION                          21
REST_TYPE                        227
DISH_LIKED                     28078
CUISINES                          45
APPROX_COST(FOR TWO PEOPLE)      346
REVIEWS_LIST                       0
MENU_ITEM                          0
LISTED_IN(TYPE)                    0
LISTED_IN(CITY)                    0
dtype: int64

In [160]:
print(keep_col.shape)
print()
keep_col.isnull().sum()

(51717, 6)

NAME                               0
ONLINE_ORDER                       0
BOOK_TABLE                         0
RATE                            7775
DISH_LIKED                     28078
APPROX_COST(FOR TWO PEOPLE)      346
dtype: int64

# to take the columns in the 6 that columns are import  to me

In [161]:
new_take_columns=copy1[columns_keep]

In [162]:
len(new_take_columns) # to take the columns in the 6 that columns are import  to me 
new_take_columns.shape

(51717, 6)

 # to drop the columns in the 11 that columns are not important  to me

In [163]:
columns_drops1=copy1[columns_drops]  # to drop the columns in the 11 that columns are not important  to me 
columns_drops1.shape

(51717, 11)

 # now i am woring in the  new_take_columns=copy1[columns_keep] fillter

In [164]:
new_take_columns.duplicated().sum()

np.int64(32808)

In [165]:
new_take_columns.duplicated().value_counts()

True     32808
False    18909
Name: count, dtype: int64

In [166]:
new_take_columns.duplicated().iloc[0:50000].value_counts()

True     31900
False    18100
Name: count, dtype: int64

new_take=copy1[columns_keep]

In [167]:
# delete the dublicate data  so
# to dubilicate

In [168]:
new_take_columns.drop_duplicates(inplace=True)

/var/folders/m5/pjzzzf8n62x495_tfwb87yrh0000gn/T/ipykernel_66942/2851206104.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_take_columns.drop_duplicates(inplace=True)

In [169]:
new_take_columns.duplicated().sum()

np.int64(0)

In [170]:
new_take_columns.isnull().sum()

NAME                               0
ONLINE_ORDER                       0
BOOK_TABLE                         0
RATE                            2418
DISH_LIKED                     10587
APPROX_COST(FOR TWO PEOPLE)      140
dtype: int64

In [171]:
new_take_columns["RATE"].isnull().sum()

np.int64(2418)

In [172]:
new_take_columns.dropna(subset=["RATE"],inplace=True)

/var/folders/m5/pjzzzf8n62x495_tfwb87yrh0000gn/T/ipykernel_66942/3383835617.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_take_columns.dropna(subset=["RATE"],inplace=True)

In [173]:
new_take_columns.isnull().sum()

NAME                              0
ONLINE_ORDER                      0
BOOK_TABLE                        0
RATE                              0
DISH_LIKED                     8199
APPROX_COST(FOR TWO PEOPLE)      99
dtype: int64

In [174]:
# now i am working i the columns DISH_LIKED

In [175]:
new_take_columns.head(9)

,NAME,ONLINE_ORDER,BOOK_TABLE,RATE,DISH_LIKED,APPROX_COST(FOR TWO PEOPLE)
0,Jalsa,Yes,Yes,4.1/5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,Yes,No,4.1/5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,Yes,No,3.8/5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,No,No,3.7/5,Masala Dosa,300
4,Grand Village,No,No,3.8/5,"Panipuri, Gol Gappe",600
5,Timepass Dinner,Yes,No,3.8/5,"Onion Rings, Pasta, Kadhai Paneer, Salads, Sal...",600
6,Rosewood International Hotel - Bar & Restaurant,No,No,3.6/5,NaN,800
7,Onesta,Yes,Yes,4.6/5,"Farmhouse Pizza, Chocolate Banana, Virgin Moji...",600
8,Penthouse Cafe,Yes,No,4.0/5,"Pizza, Mocktails, Coffee, Nachos, Salad, Pasta...",700

In [176]:
new_take_columns["DISH_LIKED"].value_counts()

DISH_LIKED
Biryani                                                                            78
Chicken Biryani                                                                    32
Paratha                                                                            28
Friendly Staff                                                                     26
Pizza                                                                              22
                                                                                   ..
Coffee, Spaghetti, Pancakes, Nachos, Pasta, Sandwich, Garlic Bread                  1
Mocktails, Peri Fries, Lasagne, Pizza, Chicken Bbq Wings, Virgin Mojito, Nachos     1
Waffles, Pasta, Crispy Chicken, Honey Chilli Chicken, Sandwich, Coffee, Crepe       1
Waffles, Pasta, Coleslaw Sandwich, Choco Waffle, Tacos, Momos, Cheese Nachos        1
Pizza, Mocktails, Coffee, Nachos, Salad, Pasta, Sandwiches                          1
Name: count, Length: 5268, dtype: int64

In [177]:
new_take_columns["DISH_LIKED"]=new_take_columns["DISH_LIKED"].fillna(method="ffill")

/var/folders/m5/pjzzzf8n62x495_tfwb87yrh0000gn/T/ipykernel_66942/2009411451.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  new_take_columns["DISH_LIKED"]=new_take_columns["DISH_LIKED"].fillna(method="ffill")
/var/folders/m5/pjzzzf8n62x495_tfwb87yrh0000gn/T/ipykernel_66942/2009411451.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_take_columns["DISH_LIKED"]=new_take_columns["DISH_LIKED"].fillna(method="ffill")

In [178]:
new_take_columns["DISH_LIKED"].value_counts().sum()

np.int64(16491)

In [179]:
new_take_columns["DISH_LIKED"].isnull().sum()

np.int64(0)

In [180]:
new_take_columns.isnull().sum()

NAME                            0
ONLINE_ORDER                    0
BOOK_TABLE                      0
RATE                            0
DISH_LIKED                      0
APPROX_COST(FOR TWO PEOPLE)    99
dtype: int64

In [181]:
new_take_columns.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16491 entries, 0 to 51677
Data columns (total 6 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   NAME                         16491 non-null  object
 1   ONLINE_ORDER                 16491 non-null  object
 2   BOOK_TABLE                   16491 non-null  object
 3   RATE                         16491 non-null  object
 4   DISH_LIKED                   16491 non-null  object
 5   APPROX_COST(FOR TWO PEOPLE)  16392 non-null  object
dtypes: object(6)
memory usage: 901.9+ KB

In [182]:
# now i am working in the  APPROX_COST(FOR TWO PEOPLE)

In [183]:
new_take_columns["APPROX_COST(FOR TWO PEOPLE)"].value_counts()

APPROX_COST(FOR TWO PEOPLE)
400      2293
300      2287
500      1681
200      1492
600      1222
         ...
4,100       1
5,000       1
120         1
3,700       1
4,500       1
Name: count, Length: 66, dtype: int64

In [184]:
type(new_take_columns["APPROX_COST(FOR TWO PEOPLE)"][9])

str

In [185]:
new_take_columns["APPROX_COST(FOR TWO PEOPLE)"].iloc[200:400]

235      450
236      450
237      150
238      250
240      250
       ...
455      200
457    1,000
459      150
461      750
462      200
Name: APPROX_COST(FOR TWO PEOPLE), Length: 200, dtype: object

In [186]:
new_take_columns["APPROX_COST(FOR TWO PEOPLE)"][80:91]

82    200
83    700
85    300
86    600
87    200
88    500
89    250
93    300
94    600
95    800
96    250
Name: APPROX_COST(FOR TWO PEOPLE), dtype: object

In [187]:
new_take_columns["APPROX_COST(FOR TWO PEOPLE)"]=new_take_columns["APPROX_COST(FOR TWO PEOPLE)"].str.replace(",","")

/var/folders/m5/pjzzzf8n62x495_tfwb87yrh0000gn/T/ipykernel_66942/3114813140.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_take_columns["APPROX_COST(FOR TWO PEOPLE)"]=new_take_columns["APPROX_COST(FOR TWO PEOPLE)"].str.replace(",","")

In [188]:
new_take_columns["APPROX_COST(FOR TWO PEOPLE)"].iloc[200:400]

235     450
236     450
237     150
238     250
240     250
       ...
455     200
457    1000
459     150
461     750
462     200
Name: APPROX_COST(FOR TWO PEOPLE), Length: 200, dtype: object

In [189]:
new_take_columns["APPROX_COST(FOR TWO PEOPLE)"]=new_take_columns["APPROX_COST(FOR TWO PEOPLE)"].str.replace(" ","")

/var/folders/m5/pjzzzf8n62x495_tfwb87yrh0000gn/T/ipykernel_66942/637926967.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_take_columns["APPROX_COST(FOR TWO PEOPLE)"]=new_take_columns["APPROX_COST(FOR TWO PEOPLE)"].str.replace(" ","")

In [190]:
new_take_columns["APPROX_COST(FOR TWO PEOPLE)"].iloc[200:400]

235     450
236     450
237     150
238     250
240     250
       ...
455     200
457    1000
459     150
461     750
462     200
Name: APPROX_COST(FOR TWO PEOPLE), Length: 200, dtype: object

In [191]:
new_take_columns["APPROX_COST(FOR TWO PEOPLE)"].isnull().sum()

np.int64(99)

In [192]:
new_take_columns["APPROX_COST(FOR TWO PEOPLE)"]=new_take_columns["APPROX_COST(FOR TWO PEOPLE)"].astype(float)

/var/folders/m5/pjzzzf8n62x495_tfwb87yrh0000gn/T/ipykernel_66942/393801972.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_take_columns["APPROX_COST(FOR TWO PEOPLE)"]=new_take_columns["APPROX_COST(FOR TWO PEOPLE)"].astype(float)

In [193]:
new_take_columns["APPROX_COST(FOR TWO PEOPLE)"]=new_take_columns["APPROX_COST(FOR TWO PEOPLE)"].fillna(new_take_columns["APPROX_COST(FOR TWO PEOPLE)"].mean())

/var/folders/m5/pjzzzf8n62x495_tfwb87yrh0000gn/T/ipykernel_66942/915243572.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_take_columns["APPROX_COST(FOR TWO PEOPLE)"]=new_take_columns["APPROX_COST(FOR TWO PEOPLE)"].fillna(new_take_columns["APPROX_COST(FOR TWO PEOPLE)"].mean())

In [194]:
new_take_columns["APPROX_COST(FOR TWO PEOPLE)"].isnull().sum()

np.int64(0)

In [195]:
new_take_columns.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16491 entries, 0 to 51677
Data columns (total 6 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   NAME                         16491 non-null  object
 1   ONLINE_ORDER                 16491 non-null  object
 2   BOOK_TABLE                   16491 non-null  object
 3   RATE                         16491 non-null  object
 4   DISH_LIKED                   16491 non-null  object
 5   APPROX_COST(FOR TWO PEOPLE)  16491 non-null  float64
dtypes: float64(1), object(5)
memory usage: 1.4+ MB

In [196]:
new_take_columns["APPROX_COST(FOR TWO PEOPLE)"]=new_take_columns["APPROX_COST(FOR TWO PEOPLE)"].astype(str)

/var/folders/m5/pjzzzf8n62x495_tfwb87yrh0000gn/T/ipykernel_66942/2005137197.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_take_columns["APPROX_COST(FOR TWO PEOPLE)"]=new_take_columns["APPROX_COST(FOR TWO PEOPLE)"].astype(str)

In [197]:
new_take_columns["APPROX_COST(FOR TWO PEOPLE)"]=new_take_columns["APPROX_COST(FOR TWO PEOPLE)"].astype(int)

ValueError: invalid literal for int() with base 10: '800.0'

In [198]:
new_take_columns["APPROX_COST(FOR TWO PEOPLE)"] = new_take_columns["APPROX_COST(FOR TWO PEOPLE)"].astype(float)

/var/folders/m5/pjzzzf8n62x495_tfwb87yrh0000gn/T/ipykernel_66942/4165747126.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_take_columns["APPROX_COST(FOR TWO PEOPLE)"] = new_take_columns["APPROX_COST(FOR TWO PEOPLE)"].astype(float)

In [199]:
new_take_columns["APPROX_COST(FOR TWO PEOPLE)"] = new_take_columns["APPROX_COST(FOR TWO PEOPLE)"].astype(int)

/var/folders/m5/pjzzzf8n62x495_tfwb87yrh0000gn/T/ipykernel_66942/1597607029.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_take_columns["APPROX_COST(FOR TWO PEOPLE)"] = new_take_columns["APPROX_COST(FOR TWO PEOPLE)"].astype(int)

In [200]:
new_take_columns["APPROX_COST(FOR TWO PEOPLE)"].value_counts()

APPROX_COST(FOR TWO PEOPLE)
400     2293
300     2287
500     1681
200     1492
600     1222
        ...
4100       1
5000       1
120        1
3700       1
4500       1
Name: count, Length: 67, dtype: int64

In [201]:
new_take_columns.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16491 entries, 0 to 51677
Data columns (total 6 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   NAME                         16491 non-null  object
 1   ONLINE_ORDER                 16491 non-null  object
 2   BOOK_TABLE                   16491 non-null  object
 3   RATE                         16491 non-null  object
 4   DISH_LIKED                   16491 non-null  object
 5   APPROX_COST(FOR TWO PEOPLE)  16491 non-null  int64
dtypes: int64(1), object(5)
memory usage: 1.4+ MB

In [202]:
new_take_columns

,NAME,ONLINE_ORDER,BOOK_TABLE,RATE,DISH_LIKED,APPROX_COST(FOR TWO PEOPLE)
0,Jalsa,Yes,Yes,4.1/5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,Yes,No,4.1/5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,Yes,No,3.8/5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,No,No,3.7/5,Masala Dosa,300
4,Grand Village,No,No,3.8/5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...
51628,Nook - Aloft Bengaluru Cessna Business Park,No,Yes,4.2 /5,"Chicken Quesadilla, Naan, Breakfast Buffet, Ch...",1800
51631,Just Parathas,No,No,3.4 /5,"Chicken Quesadilla, Naan, Breakfast Buffet, Ch...",250
51632,SeeYa Restaurant,No,No,3.3 /5,"Chicken Quesadilla, Naan, Breakfast Buffet, Ch...",350
51641,Andhra Spices,No,No,3.2 /5,"Chicken Quesadilla, Naan, Breakfast Buffet, Ch...",548
51677,Bhagini,No,No,2.5 /5,"Biryani, Andhra Meal",800

In [203]:
new_take_columns.isnull().sum()

NAME                           0
ONLINE_ORDER                   0
BOOK_TABLE                     0
RATE                           0
DISH_LIKED                     0
APPROX_COST(FOR TWO PEOPLE)    0
dtype: int64

In [204]:
new_take_columns.to_csv("Zomato_after_cleanind_data.csv")